import tseslint from 'typescript-eslint'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'

/**
 * ESLint 9 flat config for the DatXeVui frontend.
 *
 * Scope decisions:
 *  - `src/lib/api/**` is IGNORED — auto-generated by @hey-api/openapi-ts
 *    (regenerated from openapi.json; hand-tuning lint output there is
 *    thrown away on the next `bun run openapi`).
 *  - everything else IS linted: src, e2e + e2e-admin specs, scripts,
 *    and the root config files (vite/vitest/playwright configs) — a
 *    typo in an e2e fixture or a build config is just as breaking as
 *    one in app code, so they pass the same `--max-warnings 0` gate.
 *
 * CI runs `bun run lint` (= `eslint --max-warnings 0 .`) — it BLOCKS
 * the build.
 */
export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'coverage/**',
      'e2e-report/**',
      'test-results/**',
      'playwright-report/**',
      // Auto-generated OpenAPI SDK — regenerated wholesale, never hand-edited.
      'src/lib/api/**',
    ],
  },
  ...tseslint.configs.recommended,
  {
    files: ['src/**/*.{ts,tsx}'],
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    languageOptions: {
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      // react-hook-form (used by 10 forms) is not React-Compiler
      // compatible — the compiler skips memoizing those components and
      // this rule reports it. The compiler itself is not enabled in
      // this project yet, so the warnings are pure noise today.
      // Revisit when adopting babel-plugin-react-compiler.
      'react-hooks/incompatible-library': 'off',
      // Unused args prefixed with `_` are the deliberate "position must
      // stay but value unused" convention (callback signatures, hook
      // overrides).
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      // Vite HMR hygiene. The codebase deliberately co-locates constants
      // (zod schemas, cva variants, route configs) with components —
      // the shadcn convention. Splitting 39 files to appease the rule
      // is churn without user-visible gain; HMR state loss when editing
      // a co-located constant is an accepted DX tradeoff.
      'react-refresh/only-export-components': 'off',
    },
  },
  {
    files: ['src/ui-gallery/**/*.{ts,tsx}'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
)
