import { defineConfig } from '@hey-api/openapi-ts'

/**
 * SDK generation from the checked-in spec (regenerated by the backend test
 * `cargo test --lib dump_openapi_spec_for_the_frontend_sdk`).
 *
 * The backend's operationIds are bare handler names (`list`, `create`, …) that
 * repeat across modules, which would make the generator emit `list2…list15`
 * and shift them whenever an endpoint is added. `patch.input` gives every
 * operation a stable name and tags it with its owning resource:
 *
 *   GET  /api/admin/brands          list    → adminBrandsList      tag adminBrands
 *   POST /api/bookings/{id}/cancel  cancel  → bookingsCancel       tag bookings
 *   POST /api/payments              create_payment (unique) stays  tag payments
 *
 * The tag lands in every query key and mutation `meta.resource`, which
 * `src/api/query-client.ts` uses to refresh affected queries after a mutation.
 */

const METHODS = ['get', 'post', 'put', 'patch', 'delete'] as const

const camel = (s: string) => s.replace(/[-_.]+(.)/g, (_, c: string) => c.toUpperCase())
const pascal = (s: string) => s.charAt(0).toUpperCase() + s.slice(1)

const staticSegments = (path: string) =>
  path
    .replace(/^\/api\//, '')
    .split('/')
    .filter((s) => s && !s.startsWith('{'))

/** `/api/admin/brands/{id}` → `adminBrands`; `/api/bookings` → `bookings`. */
const resourceOf = (path: string) => {
  const [first = 'root', second] = staticSegments(path)
  return camel(first === 'admin' && second ? `admin-${second}` : first)
}

/** Descriptive handler names the generic rule would leave too vague. */
const OVERRIDES: Record<string, string> = {
  'PATCH /api/admin/bookings/{id}': 'adminBookingsUpdateStatus',
  'PUT /api/admin/bus-layouts/{id}/plan': 'adminBusLayoutsReplacePlan',
  'POST /api/admin/bus-layouts/{id}/plan/fit': 'adminBusLayoutsFitPlan',
}

type Operation = { operationId: string; tags?: string[] }
type Spec = { paths?: Record<string, Record<string, Operation>> }

function nameOperations(spec: Spec) {
  const ops = Object.entries(spec.paths ?? {}).flatMap(([path, item]) =>
    METHODS.filter((m) => item[m]).map((m) => ({
      key: `${m.toUpperCase()} ${path}`,
      path,
      op: item[m],
    })),
  )
  const uses = new Map<string, number>()
  for (const { op } of ops) uses.set(op.operationId, (uses.get(op.operationId) ?? 0) + 1)

  const taken = new Set<string>()
  for (const { key, path, op } of ops) {
    if (path.startsWith('/api/')) {
      const resource = resourceOf(path)
      op.tags = [resource]
      const verb = camel(op.operationId)
      const generic = !op.operationId.includes('_') || (uses.get(op.operationId) ?? 0) > 1
      if (OVERRIDES[key]) op.operationId = OVERRIDES[key]
      else if (generic) op.operationId = verb === resource ? verb : resource + pascal(verb)
    }
    if (taken.has(op.operationId))
      throw new Error(`Duplicate operationId after naming: ${op.operationId}`)
    taken.add(op.operationId)
  }
}

export default defineConfig({
  input: './openapi.json',
  output: 'src/api/generated',
  parser: { patch: { input: (spec) => nameOperations(spec as unknown as Spec) } },
  plugins: [
    '@hey-api/client-fetch',
    {
      name: '@tanstack/react-query',
      queryKeys: { tags: true },
      infiniteQueryKeys: { tags: true },
      mutationOptions: { meta: (op: { tags?: readonly string[] }) => ({ resource: op.tags?.[0] }) },
    },
  ],
})
