import { defineConfig } from '@hey-api/openapi-ts';

export default defineConfig({
    // Checked-in spec — regenerated by the backend test
    // `cargo test --lib dump_openapi_spec_for_the_frontend_sdk`
    // (writes ../frontend/openapi.json), so the SDK can be regenerated
    // offline without a running server.
    input: './openapi.json',
    output: 'src/lib/api',
    plugins: [
        '@hey-api/client-fetch',
        '@tanstack/react-query',
    ],
});