use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    paths(
        // auth
        crate::routes::auth::register,
        crate::routes::auth::login,
        crate::routes::auth::employee_login,
        crate::routes::auth::refresh,
        crate::routes::auth::logout,
        crate::routes::auth::me,
        // users
        crate::routes::users::list_users,
        crate::routes::users::get_user,
        crate::routes::users::delete_user,
        // posts
        crate::routes::posts::list_posts,
        crate::routes::posts::create_post,
        crate::routes::posts::get_post,
        crate::routes::posts::update_post,
        crate::routes::posts::delete_post,
        // price alerts
        crate::routes::price_alerts::list,
        crate::routes::price_alerts::create,
        crate::routes::price_alerts::remove,
        // health
        crate::routes::health::health,
        crate::routes::health::ready,
        // reviews
        crate::routes::reviews::list,
        crate::routes::reviews::get,
        crate::routes::reviews::create,
        crate::routes::reviews::update,
        crate::routes::reviews::remove,
        crate::routes::reviews::tags,
        // bookings
        crate::routes::bookings::list,
        crate::routes::bookings::hold,
        crate::routes::bookings::lookup,
        crate::routes::bookings::detail,
        crate::routes::bookings::cancel,
        crate::routes::bookings::confirm,
        // chat
        crate::routes::chat::list_channels,
        crate::routes::chat::create_channel,
        crate::routes::chat::list_messages,
        crate::routes::chat::post_message,
        crate::routes::chat::mark_read,
        // notifications
        crate::routes::notifications::list,
        crate::routes::notifications::mark_read,
        // wishlist
        crate::routes::wishlist::list,
        crate::routes::wishlist::toggle,
        crate::routes::wishlist::remove,
        // places
        crate::routes::places::list,
        crate::routes::places::search,
        crate::routes::places::reverse,
        // public catalog
        crate::routes::public::brands,
        crate::routes::public::brand_detail,
        crate::routes::public::routes,
        crate::routes::public::trip_detail,
        crate::routes::public::search_trips,
        crate::routes::public::recommendations,
        crate::routes::public::campaigns,
        crate::routes::public::validate_campaign,
        crate::routes::public::stats,
        // routing
        crate::routes::routing::directions,
        crate::routes::routing::matrix,
        crate::routes::routing::isochrone,
        // admin — brands
        crate::routes::admin::list_brands,
        crate::routes::admin::create_brand,
        crate::routes::admin::update_brand,
        crate::routes::admin::delete_brand,
        // admin — routes
        crate::routes::admin::list_routes,
        crate::routes::admin::create_route,
        crate::routes::admin::update_route,
        crate::routes::admin::delete_route,
        // admin — schedules
        crate::routes::admin::list_schedules,
        crate::routes::admin::create_schedule,
        crate::routes::admin::update_schedule,
        crate::routes::admin::delete_schedule,
        // admin — pickup points
        crate::routes::admin::list_pickup_points,
        crate::routes::admin::create_pickup_point,
        crate::routes::admin::update_pickup_point,
        crate::routes::admin::delete_pickup_point,
        // admin — bus layouts
        crate::routes::admin::list_bus_layouts,
        // admin — reviews moderation
        crate::routes::admin::list_reviews,
        crate::routes::admin::moderate_review,
        crate::routes::admin::delete_review,
        // admin — bookings
        crate::routes::admin::list_bookings,
        crate::routes::admin::get_booking,
        crate::routes::admin::update_booking_status,
        crate::routes::admin::booking_stats,
        crate::routes::admin::booking_export,
        // zeroclaw
        crate::routes::zeroclaw::status,
        crate::routes::zeroclaw::list_exchanges,
    ),
    components(schemas(
        // auth
        crate::routes::auth::RegisterRequest,
        crate::routes::auth::LoginRequest,
        crate::routes::auth::AuthResponse,
        // users
        crate::routes::users::UserOut,
        // posts
        crate::routes::posts::PostOut,
        crate::routes::posts::CreatePostRequest,
        crate::routes::posts::UpdatePostRequest,
        crate::routes::posts::ListPostsResponse,
        // price alerts
        crate::routes::price_alerts::PriceAlertOut,
        crate::routes::price_alerts::CreatePriceAlertRequest,
        crate::routes::price_alerts::CreatePriceAlertResponse,
        crate::routes::price_alerts::PriceAlertListEnvelope,
        // reviews
        crate::dto::review::CreateReviewInput,
        crate::dto::review::UpdateReviewInput,
        crate::dto::review::ReviewOut,
        crate::dto::review::ReviewListResponse,
        crate::dto::review::ReviewMutationResponse,
        crate::dto::review::ReviewDeleteResponse,
        crate::dto::review::ReviewTagsResponse,
        // bookings
        crate::dto::booking::HoldReq,
        crate::dto::booking::PassengerReq,
        crate::dto::booking::ConfirmReq,
        crate::dto::booking::CancelReq,
        crate::dto::booking::BookingListItem,
        crate::dto::booking::BookingListResponse,
        crate::dto::booking::BookingLookupResponse,
        crate::dto::booking::BookingHoldResponse,
        crate::dto::booking::BookingCancelResponse,
        crate::dto::booking::BookingConfirmResponse,
        crate::dto::booking::BookingSeatOut,
        crate::dto::booking::BookingTripPreview,
        crate::dto::booking::BookingRoutePreview,
        crate::dto::booking::BookingBrandPreview,
        crate::dto::booking::BookingBusLayoutPreview,
        crate::dto::booking::PickupPointOut,
        // places
        crate::dto::place::PlaceOut,
        crate::dto::place::PlaceListResponse,
        crate::dto::place::PlaceSearchHit,
        crate::dto::place::PlaceSearchResponse,
        // routing
        crate::dto::routing::DirectionsResponse,
        crate::dto::routing::MatrixResponse,
        crate::dto::routing::IsochroneResponse,
        // public catalog
        crate::dto::public::BrandOut,
        crate::dto::public::BrandDetailOut,
        crate::dto::public::BrandListResponse,
        crate::dto::public::RouteOut,
        crate::dto::public::RouteBrandPreview,
        crate::dto::public::RouteEndpoint,
        crate::dto::public::RouteListResponse,
        crate::dto::public::TripResult,
        crate::dto::public::TripSearchResponse,
        crate::dto::public::TripDetail,
        crate::dto::public::TripCore,
        crate::dto::public::TripRouteDetail,
        crate::dto::public::TripBrandDetail,
        crate::dto::public::TripEndpoint,
        crate::dto::public::TripBusLayout,
        crate::dto::public::TripPricing,
        crate::dto::public::TripAmenity,
        crate::dto::public::TripPickupPoint,
        crate::dto::public::TripSeatMap,
        crate::dto::public::TripSeatDeck,
        crate::dto::public::TripSeatRow,
        crate::dto::public::TripSeat,
        crate::dto::public::TripCampaign,
        crate::dto::public::CampaignOut,
        crate::dto::public::CampaignListResponse,
        crate::dto::public::CampaignValidateResponse,
        crate::dto::public::StatsResponse,
        // chat
        crate::dto::chat::ChatChannelOut,
        crate::dto::chat::ChatChannelListResponse,
        crate::dto::chat::ChatMessageOut,
        crate::dto::chat::ChatMessageListResponse,
        crate::dto::chat::CreateChannelRequest,
        crate::dto::chat::CreateChannelResponse,
        crate::dto::chat::CreateMessageRequest,
        crate::dto::chat::CreateMessageResponse,
        crate::dto::chat::MarkChannelReadResponse,
        // notifications
        crate::dto::notification::NotificationOut,
        crate::dto::notification::NotificationListResponse,
        crate::dto::notification::MarkNotificationsReadRequest,
        crate::dto::notification::MarkNotificationsReadResponse,
        // wishlist
        crate::dto::wishlist::WishlistItemOut,
        crate::dto::wishlist::WishlistListResponse,
        crate::dto::wishlist::ToggleWishlistRequest,
        crate::dto::wishlist::ToggleWishlistResponse,
        crate::dto::wishlist::DeleteWishlistResponse,
        // admin
        crate::dto::admin::AdminBrandOut,
        crate::dto::admin::AdminBrandListResponse,
        crate::dto::admin::AdminMutationResponse,
        crate::dto::admin::UpsertBrandRequest,
        crate::dto::admin::AdminRouteOut,
        crate::dto::admin::AdminRouteListResponse,
        crate::dto::admin::AdminPlacePreview,
        crate::dto::admin::UpsertRouteRequest,
        crate::dto::admin::AdminScheduleOut,
        crate::dto::admin::AdminScheduleListResponse,
        crate::dto::admin::UpsertScheduleRequest,
        crate::dto::admin::AdminPickupPointOut,
        crate::dto::admin::AdminPickupPointListResponse,
        crate::dto::admin::UpsertPickupPointRequest,
        crate::dto::admin::AdminBusLayoutOut,
        crate::dto::admin::AdminBusLayoutListResponse,
        crate::dto::admin::AdminReviewListResponse,
        crate::dto::admin::ModerateReviewRequest,
        crate::dto::admin::ModerateReviewResponse,
        crate::dto::admin::AdminBookingOut,
        crate::dto::admin::AdminBookingListResponse,
        crate::dto::admin::AdminBookingDetail,
        crate::dto::admin::AdminBookingDetailResponse,
        crate::dto::admin::AdminBookingSeatOut,
        crate::dto::admin::UpdateBookingStatusRequest,
        crate::dto::admin::UpdateBookingStatusResponse,
        crate::dto::admin::AdminBookingStatusUpdate,
        crate::dto::admin::AdminBookingStatsResponse,
        crate::dto::admin::AdminBookingTotals,
        crate::dto::admin::AdminBookingDayBucket,
        crate::dto::admin::AdminBookingExportResponse,
    )),
    tags(
        (name = "auth", description = "Authentication endpoints"),
        (name = "users", description = "User management"),
        (name = "posts", description = "Post management"),
        (name = "price-alerts", description = "Price-drop alert subscriptions"),
        (name = "system", description = "Health & readiness"),
        (name = "reviews", description = "Review management"),
        (name = "bookings", description = "Booking management"),
        (name = "chat", description = "Chat channels & messages"),
        (name = "notifications", description = "User notifications"),
        (name = "wishlist", description = "Saved routes / trips"),
        (name = "places", description = "Place search & geocoding (OSM)"),
        (name = "public", description = "Public catalog (brands, routes, trips, campaigns)"),
        (name = "routing", description = "Routing & directions (Valhalla proxy)"),
        (name = "admin", description = "Admin CRUD + moderation (requires employee role)"),
        (name = "zeroclaw", description = "ZeroClaw AI provider"),
    )
)]
pub struct ApiDoc;
