// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientOptions, type Config, createClient, createConfig } from './client';
import type { ClientOptions as ClientOptions2 } from './types.gen';

/**
 * The `createClientConfig()` function will be called on client initialization
 * and the returned object will become the client's initial configuration.
 *
 * You may want to initialize your client this way instead of calling
 * `setConfig()`. This is useful for example if you're using Next.js
 * to ensure your client always has the correct values.
 */
export type CreateClientConfig<T extends ClientOptions = ClientOptions2> = (override?: Config<ClientOptions & T>) => Config<Required<ClientOptions> & T>;

// Use the current origin in production (same-origin API calls).
// In dev, Vite proxies /api to localhost:8080, so we use the Vite dev
// server origin. The fallback 'http://localhost:8080' is for SSR/prerender.
const API_BASE_URL =
  typeof window !== 'undefined'
    ? window.location.origin
    : (import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8080');

export const client: Client = createClient(createConfig<ClientOptions2>({ baseUrl: API_BASE_URL }));
