//! OAuth 2.0 social-auth providers (Facebook / Google / X-Twitter).
//!
//! ## Flow
//!
//! ```text
//!  Frontend                 Backend                   Provider
//!  --------                 -------                   --------
//!  Click "Login with X" ──► GET /api/auth/oauth/<p>/start
//!                          ───────────────────────────►
//!                          ◄──── 302 redirect to provider
//!  ◄── 302 redirect ───────┘
//!  ──────────────────────────────────────────────────────►
//!                                                          (user logs in)
//!  ◄──────────────────────────────────────────────────── 302 redirect to
//!                                                          /api/auth/oauth/<p>/callback?code=...
//!  ──────────────────────► GET /api/auth/oauth/<p>/callback?code=...
//!                          ◄──── exchange code for access_token
//!                          ───────────────────────────────►
//!                          ◄──── access_token
//!                          ───── fetch user profile ──────►
//!                          ◄──── { email, name, subject, avatar }
//!                          upsert_oauth_user() ──► DB
//!                          issue_session() ──► cookies
//!                          ◄── 302 redirect to frontend (with auth cookies)
//!  ◄── 302 ───────────────┘
//!  (cookies are set; user is now logged in)
//! ```
//!
//! ## CSRF protection
//!
//! The `start` handler generates a random `state` token, stores it in
//! a short-lived signed cookie, and includes it in the redirect URL.
//! The `callback` handler verifies the cookie matches the `state`
//! query param. Without this, an attacker could trick a user into
//! completing an OAuth flow they didn't initiate (login CSRF).
//!
//! ## Adaptation
//!
//! Each provider implements [`OAuthProvider`]. The route handlers in
//! `crate::routes::auth::oauth` are provider-agnostic — they dispatch
//! to the right implementation based on the URL path segment.

pub mod facebook;
pub mod google;
pub mod twitter;

use async_trait::async_trait;
use serde::{Deserialize, Serialize};

use crate::config::OAuthProviderConfig;
use crate::error::AppError;

/// Normalized OAuth profile returned by all providers.
///
/// `subject` is the provider's stable user id — used as the unique
/// key when linking an OAuth identity to a local user account.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OAuthProfile {
    pub provider: String,
    pub subject: String,
    pub email: String,
    pub name: String,
    pub avatar_url: Option<String>,
}

/// Pluggable OAuth 2.0 provider. Each implementation handles:
///   1. Building the authorization URL (with state).
///   2. Exchanging the code for an access token.
///   3. Fetching the user profile.
#[async_trait]
pub trait OAuthProvider: Send + Sync {
    /// Display name (e.g. `"facebook"`).
    fn name(&self) -> &'static str;

    /// True if this provider is configured (client_id + secret set).
    fn is_configured(&self) -> bool;

    /// Build the authorization URL the user is redirected to.
    /// `state` is a CSRF token generated by the caller.
    /// `redirect_uri` is the backend callback URL.
    fn authorization_url(&self, state: &str, redirect_uri: &str) -> String;

    /// Exchange the authorization code for an access token.
    async fn exchange_code(&self, code: &str, redirect_uri: &str) -> Result<String, AppError>;

    /// Fetch the user profile using the access token.
    async fn fetch_profile(&self, access_token: &str) -> Result<OAuthProfile, AppError>;
}

/// Dispatch helper — construct a provider by name from the loaded config.
/// Returns `None` if the name isn't recognised or the provider isn't
/// configured (client_id/secret empty).
pub fn build_provider(name: &str, cfg: &OAuthProviderConfig) -> Option<Box<dyn OAuthProvider>> {
    let p: Box<dyn OAuthProvider> = match name {
        "facebook" => Box::new(facebook::FacebookProvider::with_credentials(cfg)),
        "google" => Box::new(google::GoogleProvider::with_credentials(cfg)),
        "twitter" => Box::new(twitter::TwitterProvider::with_credentials(cfg)),
        _ => return None,
    };
    if p.is_configured() {
        Some(p)
    } else {
        None
    }
}

/// Generate a random URL-safe state token (32 bytes → 43 base64 chars).
pub fn generate_state() -> String {
    use rand::RngCore;
    let mut bytes = [0u8; 32];
    rand::thread_rng().fill_bytes(&mut bytes);
    use_base64_url(&bytes)
}

/// Build the redirect URI for a given provider.
/// `{redirect_base_url}/api/auth/oauth/{provider}/callback`
pub fn callback_url(redirect_base_url: &str, provider: &str) -> String {
    let base = redirect_base_url.trim_end_matches('/');
    format!("{base}/api/auth/oauth/{provider}/callback")
}

fn use_base64_url(bytes: &[u8]) -> String {
    use base64::Engine as _;
    base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(bytes)
}
