//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ad_conversion")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub event: String,
    pub transaction_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub conversion_value: Option<String>,
    pub currency: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub gclid: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub wbraid: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub gbraid: Option<String>,
    #[sea_orm(default_value = "pending")]
    pub status: String,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub uploaded_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
