//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "booking_seat")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", unique_key = "BookingSeat_booking_seat_uniq")]
    pub booking_id: String,
    #[sea_orm(column_type = "Text", unique_key = "BookingSeat_booking_seat_uniq")]
    pub seat_id: String,
    pub passenger_name: Option<String>,
    pub passenger_age: Option<i64>,
    pub passenger_type: Option<String>,
    pub price: i64,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::booking::Entity",
        from = "Column::BookingId",
        to = "super::booking::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Booking,
    #[sea_orm(
        belongs_to = "super::seat::Entity",
        from = "Column::SeatId",
        to = "super::seat::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Seat,
}

impl Related<super::booking::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Booking.def()
    }
}

impl Related<super::seat::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Seat.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
