//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "booking")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub code: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_id: Option<String>,
    pub guest_name: Option<String>,
    pub guest_phone: Option<String>,
    pub guest_email: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub trip_session_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub boarding_point_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub dropping_point_id: Option<String>,
    pub adult_count: i64,
    pub child_count: i64,
    pub subtotal: i64,
    pub discount: i64,
    pub fees: i64,
    pub total: i64,
    pub currency: String,
    pub status: String,
    pub payment_method: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub campaign_applied_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub expires_at: Option<String>,
    pub contact_name: Option<String>,
    pub contact_phone: Option<String>,
    pub contact_email: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub dropoff_address: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub dropoff_lat: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub dropoff_lon: Option<f64>,
    pub dropoff_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub pickup_address: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub pickup_lat: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub pickup_lon: Option<f64>,
    pub pickup_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::booking_seat::Entity")]
    BookingSeat,
    #[sea_orm(
        belongs_to = "super::campaign::Entity",
        from = "Column::CampaignAppliedId",
        to = "super::campaign::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Campaign,
    #[sea_orm(
        belongs_to = "super::pickup_point::Entity",
        from = "Column::DroppingPointId",
        to = "super::pickup_point::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    PickupPoint2,
    #[sea_orm(
        belongs_to = "super::pickup_point::Entity",
        from = "Column::BoardingPointId",
        to = "super::pickup_point::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    PickupPoint1,
    #[sea_orm(has_many = "super::review::Entity")]
    Review,
    #[sea_orm(has_many = "super::seat_inventory::Entity")]
    SeatInventory,
    #[sea_orm(
        belongs_to = "super::trip_session::Entity",
        from = "Column::TripSessionId",
        to = "super::trip_session::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    TripSession,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    User,
}

impl Related<super::booking_seat::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookingSeat.def()
    }
}

impl Related<super::campaign::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Campaign.def()
    }
}

impl Related<super::review::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Review.def()
    }
}

impl Related<super::seat_inventory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SeatInventory.def()
    }
}

impl Related<super::trip_session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TripSession.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
