//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "brand")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub slug: String,
    pub name: String,
    pub logo_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub contact_phone: Option<String>,
    pub contact_email: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub rating: Option<f64>,
    pub status: String,
    pub accent_color: Option<String>,
    pub total_trips: i64,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bus_layout::Entity")]
    BusLayout,
    #[sea_orm(has_many = "super::campaign::Entity")]
    Campaign,
    #[sea_orm(has_many = "super::chat_channel::Entity")]
    ChatChannel,
    #[sea_orm(has_many = "super::discount_program::Entity")]
    DiscountProgram,
    #[sea_orm(has_many = "super::review::Entity")]
    Review,
    #[sea_orm(has_many = "super::route::Entity")]
    Route,
}

impl Related<super::bus_layout::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BusLayout.def()
    }
}

impl Related<super::campaign::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Campaign.def()
    }
}

impl Related<super::chat_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatChannel.def()
    }
}

impl Related<super::discount_program::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountProgram.def()
    }
}

impl Related<super::review::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Review.def()
    }
}

impl Related<super::route::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Route.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
