//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "chat_message")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "ChatMessage_clientMsgId_uniq")]
    pub channel_id: Uuid,
    pub sender_type: String,
    pub sender_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
    pub kind: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub attachments: Option<String>,
    pub status: String,
    #[sea_orm(unique_key = "ChatMessage_clientMsgId_uniq")]
    pub client_msg_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chat_channel::Entity",
        from = "Column::ChannelId",
        to = "super::chat_channel::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ChatChannel,
}

impl Related<super::chat_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatChannel.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
