//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "chat_channel")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub brand_id: Option<Uuid>,
    pub topic: Option<String>,
    pub status: String,
    pub priority: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_message_at: Option<String>,
    pub last_message_preview: Option<String>,
    pub unread_user: i64,
    pub unread_employee: i64,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub closed_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::brand::Entity",
        from = "Column::BrandId",
        to = "super::brand::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Brand,
    #[sea_orm(has_one = "super::chat_assignment::Entity")]
    ChatAssignment,
    #[sea_orm(has_many = "super::chat_channel_member::Entity")]
    ChatChannelMember,
    #[sea_orm(has_many = "super::chat_message::Entity")]
    ChatMessage,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
    #[sea_orm(has_many = "super::zero_claw_exchange::Entity")]
    ZeroClawExchange,
}

impl Related<super::brand::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Brand.def()
    }
}

impl Related<super::chat_assignment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatAssignment.def()
    }
}

impl Related<super::chat_channel_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatChannelMember.def()
    }
}

impl Related<super::chat_message::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatMessage.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::zero_claw_exchange::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ZeroClawExchange.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
