//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod permissions;
pub mod posts;
pub mod refresh_tokens;
pub mod role_permissions;
pub mod roles;
pub mod user_roles;
pub mod users;
