//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "null_claw_exchange")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub channel_id: Option<Uuid>,
    pub user_message_id: Option<Uuid>,
    pub assistant_message_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub prompt: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub completion: Option<String>,
    pub model: Option<String>,
    pub latency_ms: Option<i64>,
    pub handoff_to_human: bool,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chat_channel::Entity",
        from = "Column::ChannelId",
        to = "super::chat_channel::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ChatChannel,
    #[sea_orm(
        belongs_to = "super::chat_message::Entity",
        from = "Column::AssistantMessageId",
        to = "super::chat_message::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ChatMessage2,
    #[sea_orm(
        belongs_to = "super::chat_message::Entity",
        from = "Column::UserMessageId",
        to = "super::chat_message::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ChatMessage1,
}

impl Related<super::chat_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatChannel.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
