//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "payment")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub booking_id: Uuid,
    pub user_id: Option<Uuid>,
    pub provider: String,
    pub status: String,
    pub amount: i64,
    pub currency: String,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
    #[sea_orm(unique)]
    pub provider_txn_ref: String,
    pub provider_trans_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub gateway_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub qr_payload: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub memo: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub provider_response: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub failure_reason: Option<String>,
    pub created_by: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub collected_at: Option<String>,
    pub collected_by: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::booking::Entity",
        from = "Column::BookingId",
        to = "super::booking::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Booking,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    User,
}

impl Related<super::booking::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Booking.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
