//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "price_alert")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub phone: String,
    pub email: Option<String>,
    pub from_name: Option<String>,
    pub to_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub route_id: Option<String>,
    pub target_price: Option<i32>,
    pub frequency: String,
    pub status: String,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub expires_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::route::Entity",
        from = "Column::RouteId",
        to = "super::route::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Route,
}

impl Related<super::route::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Route.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
