//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "review")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub booking_id: Option<Uuid>,
    pub trip_session_id: Option<Uuid>,
    pub route_id: Option<Uuid>,
    pub brand_id: Option<Uuid>,
    pub author_name: Option<String>,
    pub author_phone: Option<String>,
    pub rating: i64,
    pub title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tags: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub photos: Option<String>,
    pub status: String,
    pub helpful_count: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub reply: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub replied_at: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
    pub user_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::booking::Entity",
        from = "Column::BookingId",
        to = "super::booking::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Booking,
    #[sea_orm(
        belongs_to = "super::brand::Entity",
        from = "Column::BrandId",
        to = "super::brand::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Brand,
    #[sea_orm(
        belongs_to = "super::route::Entity",
        from = "Column::RouteId",
        to = "super::route::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Route,
    #[sea_orm(
        belongs_to = "super::trip_session::Entity",
        from = "Column::TripSessionId",
        to = "super::trip_session::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    TripSession,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    User,
}

impl Related<super::booking::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Booking.def()
    }
}

impl Related<super::brand::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Brand.def()
    }
}

impl Related<super::route::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Route.def()
    }
}

impl Related<super::trip_session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TripSession.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
