//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "route_picture")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub route_id: Uuid,
    pub sort_order: i64,
    #[sea_orm(column_type = "Text")]
    pub storage_key: String,
    #[sea_orm(column_type = "Text")]
    pub thumb_key: String,
    #[sea_orm(column_len = 64, unique)]
    pub content_hash: String,
    #[sea_orm(column_len = 30)]
    pub mime_type: String,
    pub size_bytes: i64,
    pub thumb_bytes: i64,
    pub width: i64,
    pub height: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub alt_text: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::route::Entity",
        from = "Column::RouteId",
        to = "super::route::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Route,
}

impl Related<super::route::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Route.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
