//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "route")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub brand_id: Option<Uuid>,
    pub name: String,
    /// Vietnamese city slug (e.g. `"ha-noi"`, `"da-nang"`). Resolved to a
    /// display name via `crate::cities::find_by_slug`. NOT a UUID — the
    /// backend stores it as `VARCHAR(20) NOT NULL` so the route form
    /// can pass slugs directly without a `place` table lookup.
    #[sea_orm(column_type = "String(StringLen::N(20))")]
    pub start_location_id: String,
    #[sea_orm(column_type = "String(StringLen::N(20))")]
    pub end_location_id: String,
    pub status: String,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::brand::Entity",
        from = "Column::BrandId",
        to = "super::brand::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Brand,
    #[sea_orm(has_many = "super::pickup_point::Entity")]
    PickupPoint,
    #[sea_orm(has_many = "super::price_alert::Entity")]
    PriceAlert,
    #[sea_orm(has_many = "super::review::Entity")]
    Review,
    #[sea_orm(has_many = "super::schedule::Entity")]
    Schedule,
    #[sea_orm(has_many = "super::wishlist_item::Entity")]
    WishlistItem,
}

impl Related<super::brand::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Brand.def()
    }
}

impl Related<super::pickup_point::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PickupPoint.def()
    }
}

impl Related<super::price_alert::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PriceAlert.def()
    }
}

impl Related<super::review::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Review.def()
    }
}

impl Related<super::schedule::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Schedule.def()
    }
}

impl Related<super::wishlist_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WishlistItem.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
