//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "schedule")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub route_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub departure_time: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub effective_from: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub effective_to: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub days_of_week: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub bus_layout_id: Option<String>,
    pub base_price_adult: i64,
    pub base_price_child: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub amenities: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bus_layout::Entity",
        from = "Column::BusLayoutId",
        to = "super::bus_layout::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    BusLayout,
    #[sea_orm(
        belongs_to = "super::route::Entity",
        from = "Column::RouteId",
        to = "super::route::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Route,
    #[sea_orm(has_many = "super::trip_session::Entity")]
    TripSession,
}

impl Related<super::bus_layout::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BusLayout.def()
    }
}

impl Related<super::route::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Route.def()
    }
}

impl Related<super::trip_session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TripSession.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
