//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "seat")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "Seat_layout_label_uniq")]
    pub bus_layout_id: Uuid,
    #[sea_orm(unique_key = "Seat_layout_label_uniq")]
    pub seat_label: String,
    pub seat_class: Option<String>,
    pub row_num: Option<i16>,
    pub col_num: Option<i16>,
    pub is_window: bool,
    pub floor: i16,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::booking_seat::Entity")]
    BookingSeat,
    #[sea_orm(
        belongs_to = "super::bus_layout::Entity",
        from = "Column::BusLayoutId",
        to = "super::bus_layout::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    BusLayout,
    #[sea_orm(has_many = "super::seat_inventory::Entity")]
    SeatInventory,
}

impl Related<super::booking_seat::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookingSeat.def()
    }
}

impl Related<super::bus_layout::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BusLayout.def()
    }
}

impl Related<super::seat_inventory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SeatInventory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
