//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "seat_inventory")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", unique_key = "SeatInventory_trip_seat_uniq")]
    pub trip_session_id: String,
    #[sea_orm(column_type = "Text", unique_key = "SeatInventory_trip_seat_uniq")]
    pub seat_id: String,
    pub status: String,
    pub base_price: i64,
    pub final_price: i64,
    pub currency: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub held_until: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub held_by_booking_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::booking::Entity",
        from = "Column::HeldByBookingId",
        to = "super::booking::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Booking,
    #[sea_orm(
        belongs_to = "super::seat::Entity",
        from = "Column::SeatId",
        to = "super::seat::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Seat,
    #[sea_orm(
        belongs_to = "super::trip_session::Entity",
        from = "Column::TripSessionId",
        to = "super::trip_session::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    TripSession,
}

impl Related<super::booking::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Booking.def()
    }
}

impl Related<super::seat::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Seat.def()
    }
}

impl Related<super::trip_session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TripSession.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
