//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "trip_session")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique_key = "TripSession_schedule_date_uniq")]
    pub schedule_id: String,
    #[sea_orm(column_type = "Text", unique_key = "TripSession_schedule_date_uniq")]
    pub departure_date: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub actual_departure_at: Option<String>,
    pub driver_name: Option<String>,
    pub driver_phone: Option<String>,
    pub status: String,
    pub total_seats: i64,
    pub available_seats: i64,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::booking::Entity")]
    Booking,
    #[sea_orm(has_many = "super::review::Entity")]
    Review,
    #[sea_orm(
        belongs_to = "super::schedule::Entity",
        from = "Column::ScheduleId",
        to = "super::schedule::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Schedule,
    #[sea_orm(has_many = "super::seat_inventory::Entity")]
    SeatInventory,
}

impl Related<super::booking::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Booking.def()
    }
}

impl Related<super::review::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Review.def()
    }
}

impl Related<super::schedule::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Schedule.def()
    }
}

impl Related<super::seat_inventory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SeatInventory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
