//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub brand_id: Option<Uuid>,
    pub full_name: String,
    #[sea_orm(unique)]
    pub email: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub phone: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub email_verified_at: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub phone_verified_at: Option<String>,
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub block_reason: Option<String>,
    pub password_hash: Option<String>,
    pub avatar_url: Option<String>,
    pub locale: String,
    pub is_guest: bool,
    pub role: String,
    pub failed_login_attempts: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub locked_until: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_login_at: Option<String>,
    pub last_login_ip: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub password_changed_at: Option<String>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub oauth_provider: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub oauth_subject: Option<String>,
    pub is_bot: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::booking::Entity")]
    Booking,
    #[sea_orm(has_many = "super::chat_channel::Entity")]
    ChatChannel,
    #[sea_orm(has_many = "super::chat_channel_member::Entity")]
    ChatChannelMember,
    #[sea_orm(has_many = "super::notification::Entity")]
    Notification,
    #[sea_orm(has_many = "super::payment::Entity")]
    Payment,
    #[sea_orm(has_many = "super::posts::Entity")]
    Posts,
    #[sea_orm(has_many = "super::refresh_tokens::Entity")]
    RefreshTokens,
    #[sea_orm(has_many = "super::review::Entity")]
    Review,
    #[sea_orm(has_many = "super::user_roles::Entity")]
    UserRoles,
    #[sea_orm(has_many = "super::user_verification::Entity")]
    UserVerification,
    #[sea_orm(has_many = "super::wishlist_item::Entity")]
    WishlistItem,
}

impl Related<super::booking::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Booking.def()
    }
}

impl Related<super::chat_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatChannel.def()
    }
}

impl Related<super::chat_channel_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatChannelMember.def()
    }
}

impl Related<super::notification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notification.def()
    }
}

impl Related<super::payment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Payment.def()
    }
}

impl Related<super::posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Posts.def()
    }
}

impl Related<super::refresh_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RefreshTokens.def()
    }
}

impl Related<super::review::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Review.def()
    }
}

impl Related<super::user_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRoles.def()
    }
}

impl Related<super::user_verification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserVerification.def()
    }
}

impl Related<super::wishlist_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WishlistItem.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_roles::Relation::Roles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_roles::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
