// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { brandDetail, brands, campaigns, cancel, confirm, create, create2, createPost, deletePost, deleteUser, detail, directions, employeeLogin, get, getPost, getUser, health, hold, isochrone, list, list2, list3, list4, listChannels, listExchanges, listMessages, listPosts, listUsers, login, logout, lookup, markRead, matrix, me, type Options, ready, recommendations, refresh, register, remove, remove2, reverse, routes, search, searchTrips, stats, status, tags, tripDetail, update, updatePost, validateCampaign } from '../sdk.gen';
import type { BrandDetailData, BrandDetailResponse, BrandsData, BrandsResponse, CampaignsData, CampaignsResponse, CancelData, CancelResponse, ConfirmData, ConfirmResponse, Create2Data, Create2Response, CreateData, CreatePostData, CreatePostResponse, CreateResponse, DeletePostData, DeletePostResponse, DeleteUserData, DeleteUserResponse, DetailData, DetailResponse, DirectionsData, DirectionsResponse2, EmployeeLoginData, EmployeeLoginResponse, GetData, GetPostData, GetPostResponse, GetResponse, GetUserData, GetUserResponse, HealthData, HealthResponse2, HoldData, HoldResponse, IsochroneData, IsochroneResponse2, List2Data, List2Response, List3Data, List3Response, List4Data, List4Response, ListChannelsData, ListData, ListExchangesData, ListMessagesData, ListPostsData, ListPostsResponse2, ListResponse, ListUsersData, ListUsersResponse, LoginData, LoginResponse, LogoutData, LogoutResponse, LookupData, LookupResponse, MarkReadData, MatrixData, MatrixResponse2, MeData, MeResponse, ReadyData, ReadyError, ReadyResponse, RecommendationsData, RecommendationsResponse, RefreshData, RefreshResponse, RegisterData, RegisterResponse, Remove2Data, Remove2Response, RemoveData, RemoveResponse, ReverseData, ReverseResponse, RoutesData, RoutesResponse, SearchData, SearchResponse, SearchTripsData, SearchTripsResponse, StatsData, StatsResponse2, StatusData, TagsData, TagsResponse, TripDetailData, TripDetailResponse, UpdateData, UpdatePostData, UpdatePostResponse, UpdateResponse, ValidateCampaignData, ValidateCampaignResponse } from '../types.gen';

/**
 * `POST /api/auth/employee-login` — employee-only login (rejects regular users).
 */
export const employeeLoginMutation = (options?: Partial<Options<EmployeeLoginData>>): UseMutationOptions<EmployeeLoginResponse, DefaultError, Options<EmployeeLoginData>> => {
    const mutationOptions: UseMutationOptions<EmployeeLoginResponse, DefaultError, Options<EmployeeLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await employeeLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * `POST /api/auth/login` — exchange credentials for cookies.
 */
export const loginMutation = (options?: Partial<Options<LoginData>>): UseMutationOptions<LoginResponse, DefaultError, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<LoginResponse, DefaultError, Options<LoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * `POST /api/auth/logout` — revoke all refresh tokens + clear cookies.
 */
export const logoutMutation = (options?: Partial<Options<LogoutData>>): UseMutationOptions<LogoutResponse, DefaultError, Options<LogoutData>> => {
    const mutationOptions: UseMutationOptions<LogoutResponse, DefaultError, Options<LogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const meQueryKey = (options?: Options<MeData>) => createQueryKey('me', options);

/**
 * `GET /api/auth/me` — return the current authenticated user's info.
 */
export const meOptions = (options?: Options<MeData>) => queryOptions<MeResponse, DefaultError, MeResponse, ReturnType<typeof meQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await me({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: meQueryKey(options)
});

/**
 * `POST /api/auth/refresh` — rotate refresh token, issue new access.
 */
export const refreshMutation = (options?: Partial<Options<RefreshData>>): UseMutationOptions<RefreshResponse, DefaultError, Options<RefreshData>> => {
    const mutationOptions: UseMutationOptions<RefreshResponse, DefaultError, Options<RefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await refresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * `POST /api/auth/register` — create a new user account.
 */
export const registerMutation = (options?: Partial<Options<RegisterData>>): UseMutationOptions<RegisterResponse, DefaultError, Options<RegisterData>> => {
    const mutationOptions: UseMutationOptions<RegisterResponse, DefaultError, Options<RegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await register({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listQueryKey = (options?: Options<ListData>) => createQueryKey('list', options);

/**
 * `GET /api/bookings` — list the authenticated user's bookings.
 */
export const listOptions = (options?: Options<ListData>) => queryOptions<ListResponse, DefaultError, ListResponse, ReturnType<typeof listQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await list({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const listInfiniteQueryKey = (options?: Options<ListData>): QueryKey<Options<ListData>> => createQueryKey('list', options, true);

/**
 * `GET /api/bookings` — list the authenticated user's bookings.
 */
export const listInfiniteOptions = (options?: Options<ListData>) => {
    const opts = infiniteQueryOptions<ListResponse, DefaultError, InfiniteData<ListResponse>, QueryKey<Options<ListData>>, number | null | Pick<QueryKey<Options<ListData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<ListData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await list({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

/**
 * `POST /api/bookings` and `POST /api/bookings/hold` — hold seats for a booking.
 */
export const holdMutation = (options?: Partial<Options<HoldData>>): UseMutationOptions<HoldResponse, DefaultError, Options<HoldData>> => {
    const mutationOptions: UseMutationOptions<HoldResponse, DefaultError, Options<HoldData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await hold({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const lookupQueryKey = (options?: Options<LookupData>) => createQueryKey('lookup', options);

/**
 * `GET /api/bookings/lookup` — lookup a booking by phone or code.
 */
export const lookupOptions = (options?: Options<LookupData>) => queryOptions<LookupResponse, DefaultError, LookupResponse, ReturnType<typeof lookupQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await lookup({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: lookupQueryKey(options)
});

export const detailQueryKey = (options: Options<DetailData>) => createQueryKey('detail', options);

/**
 * `GET /api/bookings/{id}` — get booking detail.
 */
export const detailOptions = (options: Options<DetailData>) => queryOptions<DetailResponse, DefaultError, DetailResponse, ReturnType<typeof detailQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await detail({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: detailQueryKey(options)
});

/**
 * `POST /api/bookings/{id}/cancel` — cancel a booking.
 */
export const cancelMutation = (options?: Partial<Options<CancelData>>): UseMutationOptions<CancelResponse, DefaultError, Options<CancelData>> => {
    const mutationOptions: UseMutationOptions<CancelResponse, DefaultError, Options<CancelData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await cancel({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * `POST /api/bookings/{id}/confirm` — confirm a booking with payment.
 */
export const confirmMutation = (options?: Partial<Options<ConfirmData>>): UseMutationOptions<ConfirmResponse, DefaultError, Options<ConfirmData>> => {
    const mutationOptions: UseMutationOptions<ConfirmResponse, DefaultError, Options<ConfirmData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await confirm({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const brandsQueryKey = (options?: Options<BrandsData>) => createQueryKey('brands', options);

/**
 * `GET /api/brands` — list brands.
 */
export const brandsOptions = (options?: Options<BrandsData>) => queryOptions<BrandsResponse, DefaultError, BrandsResponse, ReturnType<typeof brandsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await brands({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: brandsQueryKey(options)
});

export const brandDetailQueryKey = (options: Options<BrandDetailData>) => createQueryKey('brandDetail', options);

/**
 * `GET /api/brands/{slug}` — get brand detail.
 */
export const brandDetailOptions = (options: Options<BrandDetailData>) => queryOptions<BrandDetailResponse, DefaultError, BrandDetailResponse, ReturnType<typeof brandDetailQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await brandDetail({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: brandDetailQueryKey(options)
});

export const campaignsQueryKey = (options?: Options<CampaignsData>) => createQueryKey('campaigns', options);

/**
 * `GET /api/campaigns` — list campaigns.
 */
export const campaignsOptions = (options?: Options<CampaignsData>) => queryOptions<CampaignsResponse, DefaultError, CampaignsResponse, ReturnType<typeof campaignsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await campaigns({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: campaignsQueryKey(options)
});

export const validateCampaignQueryKey = (options: Options<ValidateCampaignData>) => createQueryKey('validateCampaign', options);

/**
 * `GET /api/campaigns/validate` — validate a campaign code.
 */
export const validateCampaignOptions = (options: Options<ValidateCampaignData>) => queryOptions<ValidateCampaignResponse, DefaultError, ValidateCampaignResponse, ReturnType<typeof validateCampaignQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await validateCampaign({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: validateCampaignQueryKey(options)
});

export const listChannelsQueryKey = (options?: Options<ListChannelsData>) => createQueryKey('listChannels', options);

/**
 * `GET /api/chat/channels` — list chat channels for the authenticated user.
 */
export const listChannelsOptions = (options?: Options<ListChannelsData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof listChannelsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listChannels({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listChannelsQueryKey(options)
});

export const listMessagesQueryKey = (options: Options<ListMessagesData>) => createQueryKey('listMessages', options);

/**
 * `GET /api/chat/channels/{id}/messages` — list messages in a channel.
 */
export const listMessagesOptions = (options: Options<ListMessagesData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof listMessagesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listMessages({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listMessagesQueryKey(options)
});

export const listMessagesInfiniteQueryKey = (options: Options<ListMessagesData>): QueryKey<Options<ListMessagesData>> => createQueryKey('listMessages', options, true);

/**
 * `GET /api/chat/channels/{id}/messages` — list messages in a channel.
 */
export const listMessagesInfiniteOptions = (options: Options<ListMessagesData>) => {
    const opts = infiniteQueryOptions<unknown, DefaultError, InfiniteData<unknown>, QueryKey<Options<ListMessagesData>>, number | null | Pick<QueryKey<Options<ListMessagesData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<ListMessagesData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await listMessages({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listMessagesInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

/**
 * `POST /api/chat/channels/{id}/read` — mark messages as read.
 */
export const markReadMutation = (options?: Partial<Options<MarkReadData>>): UseMutationOptions<unknown, DefaultError, Options<MarkReadData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<MarkReadData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await markRead({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const list2QueryKey = (options?: Options<List2Data>) => createQueryKey('list2', options);

/**
 * `GET /api/places` — list places.
 */
export const list2Options = (options?: Options<List2Data>) => queryOptions<List2Response, DefaultError, List2Response, ReturnType<typeof list2QueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await list2({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: list2QueryKey(options)
});

export const list2InfiniteQueryKey = (options?: Options<List2Data>): QueryKey<Options<List2Data>> => createQueryKey('list2', options, true);

/**
 * `GET /api/places` — list places.
 */
export const list2InfiniteOptions = (options?: Options<List2Data>) => {
    const opts = infiniteQueryOptions<List2Response, DefaultError, InfiniteData<List2Response>, QueryKey<Options<List2Data>>, number | null | Pick<QueryKey<Options<List2Data>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<List2Data>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await list2({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: list2InfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

export const reverseQueryKey = (options: Options<ReverseData>) => createQueryKey('reverse', options);

/**
 * `GET /api/places/reverse` — reverse geocode coordinates.
 */
export const reverseOptions = (options: Options<ReverseData>) => queryOptions<ReverseResponse, DefaultError, ReverseResponse, ReturnType<typeof reverseQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await reverse({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: reverseQueryKey(options)
});

export const searchQueryKey = (options: Options<SearchData>) => createQueryKey('search', options);

/**
 * `GET /api/places/search` — search places by query.
 */
export const searchOptions = (options: Options<SearchData>) => queryOptions<SearchResponse, DefaultError, SearchResponse, ReturnType<typeof searchQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await search({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: searchQueryKey(options)
});

export const listPostsQueryKey = (options?: Options<ListPostsData>) => createQueryKey('listPosts', options);

/**
 * `GET /api/posts` — list posts (public read).
 */
export const listPostsOptions = (options?: Options<ListPostsData>) => queryOptions<ListPostsResponse2, DefaultError, ListPostsResponse2, ReturnType<typeof listPostsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listPosts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listPostsQueryKey(options)
});

export const listPostsInfiniteQueryKey = (options?: Options<ListPostsData>): QueryKey<Options<ListPostsData>> => createQueryKey('listPosts', options, true);

/**
 * `GET /api/posts` — list posts (public read).
 */
export const listPostsInfiniteOptions = (options?: Options<ListPostsData>) => {
    const opts = infiniteQueryOptions<ListPostsResponse2, DefaultError, InfiniteData<ListPostsResponse2>, QueryKey<Options<ListPostsData>>, number | null | Pick<QueryKey<Options<ListPostsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<ListPostsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await listPosts({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listPostsInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

/**
 * `POST /api/posts` — create a post. Requires `posts:write`.
 */
export const createPostMutation = (options?: Partial<Options<CreatePostData>>): UseMutationOptions<CreatePostResponse, DefaultError, Options<CreatePostData>> => {
    const mutationOptions: UseMutationOptions<CreatePostResponse, DefaultError, Options<CreatePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * `DELETE /api/posts/{id}` — delete a post. Requires `posts:delete`.
 */
export const deletePostMutation = (options?: Partial<Options<DeletePostData>>): UseMutationOptions<DeletePostResponse, DefaultError, Options<DeletePostData>> => {
    const mutationOptions: UseMutationOptions<DeletePostResponse, DefaultError, Options<DeletePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deletePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getPostQueryKey = (options: Options<GetPostData>) => createQueryKey('getPost', options);

/**
 * `GET /api/posts/{id}` — get a post.
 */
export const getPostOptions = (options: Options<GetPostData>) => queryOptions<GetPostResponse, DefaultError, GetPostResponse, ReturnType<typeof getPostQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPost({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPostQueryKey(options)
});

/**
 * `PATCH /api/posts/{id}` — update a post. Requires `posts:write`.
 */
export const updatePostMutation = (options?: Partial<Options<UpdatePostData>>): UseMutationOptions<UpdatePostResponse, DefaultError, Options<UpdatePostData>> => {
    const mutationOptions: UseMutationOptions<UpdatePostResponse, DefaultError, Options<UpdatePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updatePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const list3QueryKey = (options?: Options<List3Data>) => createQueryKey('list3', options);

/**
 * `GET /api/price-alerts` — list price alerts.
 *
 * - If `phone` is provided: guest lookup (public, no auth required).
 * - Otherwise: returns the authenticated user's alerts.
 */
export const list3Options = (options?: Options<List3Data>) => queryOptions<List3Response, DefaultError, List3Response, ReturnType<typeof list3QueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await list3({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: list3QueryKey(options)
});

export const list3InfiniteQueryKey = (options?: Options<List3Data>): QueryKey<Options<List3Data>> => createQueryKey('list3', options, true);

/**
 * `GET /api/price-alerts` — list price alerts.
 *
 * - If `phone` is provided: guest lookup (public, no auth required).
 * - Otherwise: returns the authenticated user's alerts.
 */
export const list3InfiniteOptions = (options?: Options<List3Data>) => {
    const opts = infiniteQueryOptions<List3Response, DefaultError, InfiniteData<List3Response>, QueryKey<Options<List3Data>>, number | Pick<QueryKey<Options<List3Data>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<List3Data>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await list3({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: list3InfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

/**
 * `POST /api/price-alerts` — create a price alert.
 *
 * Requires authentication. The authenticated user becomes the alert
 * owner. The `phone` field is still required (for notification
 * delivery) and must match a valid Vietnamese mobile number.
 */
export const createMutation = (options?: Partial<Options<CreateData>>): UseMutationOptions<CreateResponse, DefaultError, Options<CreateData>> => {
    const mutationOptions: UseMutationOptions<CreateResponse, DefaultError, Options<CreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await create({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * `DELETE /api/price-alerts/{id}` — cancel a price alert.
 *
 * Requires authentication. Only the alert's owner may cancel it.
 */
export const removeMutation = (options?: Partial<Options<RemoveData>>): UseMutationOptions<RemoveResponse, DefaultError, Options<RemoveData>> => {
    const mutationOptions: UseMutationOptions<RemoveResponse, DefaultError, Options<RemoveData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await remove({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const recommendationsQueryKey = (options?: Options<RecommendationsData>) => createQueryKey('recommendations', options);

/**
 * `GET /api/recommendations` — get trip recommendations.
 */
export const recommendationsOptions = (options?: Options<RecommendationsData>) => queryOptions<RecommendationsResponse, DefaultError, RecommendationsResponse, ReturnType<typeof recommendationsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await recommendations({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: recommendationsQueryKey(options)
});

export const list4QueryKey = (options?: Options<List4Data>) => createQueryKey('list4', options);

/**
 * `GET /api/reviews` — list reviews with optional filters.
 */
export const list4Options = (options?: Options<List4Data>) => queryOptions<List4Response, DefaultError, List4Response, ReturnType<typeof list4QueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await list4({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: list4QueryKey(options)
});

export const list4InfiniteQueryKey = (options?: Options<List4Data>): QueryKey<Options<List4Data>> => createQueryKey('list4', options, true);

/**
 * `GET /api/reviews` — list reviews with optional filters.
 */
export const list4InfiniteOptions = (options?: Options<List4Data>) => {
    const opts = infiniteQueryOptions<List4Response, DefaultError, InfiniteData<List4Response>, QueryKey<Options<List4Data>>, number | null | Pick<QueryKey<Options<List4Data>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<List4Data>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await list4({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: list4InfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

/**
 * `POST /api/reviews` — create a review. Requires authentication.
 */
export const create2Mutation = (options?: Partial<Options<Create2Data>>): UseMutationOptions<Create2Response, DefaultError, Options<Create2Data>> => {
    const mutationOptions: UseMutationOptions<Create2Response, DefaultError, Options<Create2Data>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await create2({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const tagsQueryKey = (options?: Options<TagsData>) => createQueryKey('tags', options);

/**
 * `GET /api/reviews/tags` — get the review tags index.
 */
export const tagsOptions = (options?: Options<TagsData>) => queryOptions<TagsResponse, DefaultError, TagsResponse, ReturnType<typeof tagsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await tags({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: tagsQueryKey(options)
});

/**
 * `DELETE /api/reviews/{id}` — delete a review. Requires authentication.
 */
export const remove2Mutation = (options?: Partial<Options<Remove2Data>>): UseMutationOptions<Remove2Response, DefaultError, Options<Remove2Data>> => {
    const mutationOptions: UseMutationOptions<Remove2Response, DefaultError, Options<Remove2Data>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await remove2({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getQueryKey = (options: Options<GetData>) => createQueryKey('get', options);

/**
 * `GET /api/reviews/{id}` — get a review by ID.
 */
export const getOptions = (options: Options<GetData>) => queryOptions<GetResponse, DefaultError, GetResponse, ReturnType<typeof getQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await get({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getQueryKey(options)
});

/**
 * `PATCH /api/reviews/{id}` — update a review. Requires authentication.
 */
export const updateMutation = (options?: Partial<Options<UpdateData>>): UseMutationOptions<UpdateResponse, DefaultError, Options<UpdateData>> => {
    const mutationOptions: UseMutationOptions<UpdateResponse, DefaultError, Options<UpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await update({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const routesQueryKey = (options?: Options<RoutesData>) => createQueryKey('routes', options);

/**
 * `GET /api/routes` — list routes.
 */
export const routesOptions = (options?: Options<RoutesData>) => queryOptions<RoutesResponse, DefaultError, RoutesResponse, ReturnType<typeof routesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await routes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: routesQueryKey(options)
});

export const directionsQueryKey = (options: Options<DirectionsData>) => createQueryKey('directions', options);

/**
 * `GET /api/routing/directions` — get directions between locations.
 */
export const directionsOptions = (options: Options<DirectionsData>) => queryOptions<DirectionsResponse2, DefaultError, DirectionsResponse2, ReturnType<typeof directionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await directions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: directionsQueryKey(options)
});

export const isochroneQueryKey = (options: Options<IsochroneData>) => createQueryKey('isochrone', options);

/**
 * `GET /api/routing/isochrone` — compute isochrone contours.
 */
export const isochroneOptions = (options: Options<IsochroneData>) => queryOptions<IsochroneResponse2, DefaultError, IsochroneResponse2, ReturnType<typeof isochroneQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await isochrone({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: isochroneQueryKey(options)
});

export const matrixQueryKey = (options: Options<MatrixData>) => createQueryKey('matrix', options);

/**
 * `GET /api/routing/matrix` — compute distance/time matrix.
 */
export const matrixOptions = (options: Options<MatrixData>) => queryOptions<MatrixResponse2, DefaultError, MatrixResponse2, ReturnType<typeof matrixQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await matrix({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: matrixQueryKey(options)
});

export const searchTripsQueryKey = (options: Options<SearchTripsData>) => createQueryKey('searchTrips', options);

/**
 * `GET /api/search` — search trips.
 */
export const searchTripsOptions = (options: Options<SearchTripsData>) => queryOptions<SearchTripsResponse, DefaultError, SearchTripsResponse, ReturnType<typeof searchTripsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await searchTrips({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: searchTripsQueryKey(options)
});

export const statsQueryKey = (options?: Options<StatsData>) => createQueryKey('stats', options);

/**
 * `GET /api/stats` — get public stats.
 */
export const statsOptions = (options?: Options<StatsData>) => queryOptions<StatsResponse2, DefaultError, StatsResponse2, ReturnType<typeof statsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await stats({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: statsQueryKey(options)
});

export const tripDetailQueryKey = (options: Options<TripDetailData>) => createQueryKey('tripDetail', options);

/**
 * `GET /api/trips/{id}` — get trip detail.
 */
export const tripDetailOptions = (options: Options<TripDetailData>) => queryOptions<TripDetailResponse, DefaultError, TripDetailResponse, ReturnType<typeof tripDetailQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await tripDetail({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: tripDetailQueryKey(options)
});

export const listUsersQueryKey = (options?: Options<ListUsersData>) => createQueryKey('listUsers', options);

/**
 * `GET /api/users` — list users. Requires `users:read`.
 */
export const listUsersOptions = (options?: Options<ListUsersData>) => queryOptions<ListUsersResponse, DefaultError, ListUsersResponse, ReturnType<typeof listUsersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listUsers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listUsersQueryKey(options)
});

/**
 * `DELETE /api/users/{id}` — delete a user. Requires `users:delete`.
 */
export const deleteUserMutation = (options?: Partial<Options<DeleteUserData>>): UseMutationOptions<DeleteUserResponse, DefaultError, Options<DeleteUserData>> => {
    const mutationOptions: UseMutationOptions<DeleteUserResponse, DefaultError, Options<DeleteUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUserQueryKey = (options: Options<GetUserData>) => createQueryKey('getUser', options);

/**
 * `GET /api/users/{id}` — get a user. Requires `users:read`.
 */
export const getUserOptions = (options: Options<GetUserData>) => queryOptions<GetUserResponse, DefaultError, GetUserResponse, ReturnType<typeof getUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserQueryKey(options)
});

export const listExchangesQueryKey = (options?: Options<ListExchangesData>) => createQueryKey('listExchanges', options);

/**
 * `GET /api/zeroclaw/exchanges` — list ZeroClaw exchanges.
 */
export const listExchangesOptions = (options?: Options<ListExchangesData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof listExchangesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listExchanges({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listExchangesQueryKey(options)
});

export const listExchangesInfiniteQueryKey = (options?: Options<ListExchangesData>): QueryKey<Options<ListExchangesData>> => createQueryKey('listExchanges', options, true);

/**
 * `GET /api/zeroclaw/exchanges` — list ZeroClaw exchanges.
 */
export const listExchangesInfiniteOptions = (options?: Options<ListExchangesData>) => {
    const opts = infiniteQueryOptions<unknown, DefaultError, InfiniteData<unknown>, QueryKey<Options<ListExchangesData>>, number | null | Pick<QueryKey<Options<ListExchangesData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<ListExchangesData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await listExchanges({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listExchangesInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

export const statusQueryKey = (options?: Options<StatusData>) => createQueryKey('status', options);

/**
 * `GET /api/zeroclaw/status` — get ZeroClaw provider status.
 */
export const statusOptions = (options?: Options<StatusData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof statusQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await status({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: statusQueryKey(options)
});

export const healthQueryKey = (options?: Options<HealthData>) => createQueryKey('health', options);

/**
 * `GET /health` — liveness probe. Always returns 200 (process is up).
 */
export const healthOptions = (options?: Options<HealthData>) => queryOptions<HealthResponse2, DefaultError, HealthResponse2, ReturnType<typeof healthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await health({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthQueryKey(options)
});

export const readyQueryKey = (options?: Options<ReadyData>) => createQueryKey('ready', options);

/**
 * `GET /ready` — readiness probe. Actually pings the DB.
 * Returns 503 if the DB is unreachable so load balancers won't route here.
 */
export const readyOptions = (options?: Options<ReadyData>) => queryOptions<ReadyResponse, ReadyError, ReadyResponse, ReturnType<typeof readyQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ready({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readyQueryKey(options)
});
