/**
 * Shared display constants + local UI-only types for the Admin module.
 *
 * Entity types (Brand, Route, Schedule, PickupPoint, BusLayout, Place)
 * are now imported from `@/lib/api/types.gen` (auto-generated by
 * openapi-ts) — they match the backend exactly. This file only keeps
 * constants and UI-only discriminated unions that don't have a backend
 * counterpart.
 */

import { Wifi, Snowflake, Droplet, Plug, type LucideIcon } from 'lucide-react'

/** Compact day-chip labels — I18N KEYS (T2…CN / Mo…Su), resolved at
 *  render time via `t(...)` / `translate(...)` by consumers. */
export const DAY_LABELS = [
  'common.dayShort.mon',
  'common.dayShort.tue',
  'common.dayShort.wed',
  'common.dayShort.thu',
  'common.dayShort.fri',
  'common.dayShort.sat',
  'common.dayShort.sun',
]

/** Vehicle-class labels — I18N KEYS, resolved at render time. */
export const VEHICLE_LABELS: Record<string, string> = {
  limousine: 'types.vehicleLimousine',
  sleeper: 'types.vehicleSleeper',
  semi_sleeper: 'adminShared.vehicleSemiSleeper',
  standard: 'types.vehicleStandard',
  minivan: 'types.vehicleMinivan',
}

/** Amenity chips for the schedule form — labels are plain fallback text
 *  (schedule-pricing-fields.tsx maps every key to an i18n key at render
 *  time via its AMENITY_KEYS map, so these literals only surface if the
 *  map ever misses — kept as human-readable slugs). */
export const AMENITY_OPTIONS: { key: string; label: string; icon: LucideIcon }[] = [
  { key: 'wifi', label: 'Wifi', icon: Wifi },
  { key: 'ac', label: 'AC', icon: Snowflake },
  { key: 'water', label: 'Water', icon: Droplet },
  { key: 'charging', label: 'Charging', icon: Plug },
]

/** Pickup point kind labels — I18N KEYS, resolved at render time. */
export const PICKUP_TYPE_LABELS: Record<string, string> = {
  station: 'adminPickup.type.station',
  curb: 'adminPickup.type.curb',
  on_request: 'adminPickup.type.onRequest',
}

/** Discriminated union used by the delete-confirmation AlertDialog. */
export type DeleteTarget =
  | { kind: 'brand'; id: string; name: string }
  | { kind: 'route'; id: string; name: string }
  | { kind: 'schedule'; id: string; name: string }
  | { kind: 'pickup'; id: string; name: string }
  | null
