#!/usr/bin/env bash
# VeXeVN (datxevui.com) — idempotent Swarm-stack deploy on the shared node.
#
# Run by GitHub Actions (.github/workflows/deploy.yml) after each tag build:
#   IMAGE=ghcr.io/iamleson98/rust-be-template:v0.1.0 bash deploy.sh
#
# Expects next to this script: stack.yml, Caddyfile.datxevui
# Creates .env on the FIRST run (random JWT secret, 0600) — secrets are
# generated on the server and never leave it.
#
# What it does:
#   1. first-run .env           (JWT_SECRET via openssl)
#   2. optional GHCR login      (private packages only)
#   3. docker stack deploy      (pulls $IMAGE, volumes persist)
#   4. appends the datxevui.com site block to the shared Caddyfile once
#   5. hot-reloads Caddy        (zero downtime; restart fallback)
#   6. health gate: /health on the NEW backend task (verified against
#      the service spec image — detects swarm auto-rollback; retries
#      once on the transient "lease does not exist" rejection)
#
# Rollback on failure (documented, manual):
#   docker service update --image <PREV_IMAGE> vexevn_backend
set -euo pipefail

cd "$(cd "$(dirname "$0")" && pwd)"

STACK=datxevui
SHARED_CADDYFILE=/opt/pdf-tts/Caddyfile
MARKER='# datxevui-datxevui'

[ -f stack.yml ]          || { echo "FATAL: stack.yml missing in $(pwd)"; exit 1; }
[ -f Caddyfile.datxevui ] || { echo "FATAL: Caddyfile.datxevui missing in $(pwd)"; exit 1; }

# ── 1. First-run .env (secrets generated ON the server) ──────────────
if [ ! -f .env ]; then
  umask 077
  cat > .env <<EOF
# datxevui production env — generated by deploy.sh on first run.
# Non-secret defaults live in stack.yml; edit values here to override.
JWT_SECRET=$(openssl rand -hex 32)
EOF
  echo ".env created with a fresh random JWT_SECRET (0600)"
fi

# Export .env values so stack.yml ${VAR} interpolation picks them up.
set -a; . ./.env; set +a

# The CD pipeline passes the exact image ref; manual runs may set it too.
: "${IMAGE:?IMAGE=<image-ref> env var is required (set by the CD pipeline)}"
: "${JWT_SECRET:?JWT_SECRET missing — check .env}"

# ── 2. Optional GHCR login (private packages only) ───────────────────
# The node usually already has ghcr.io credentials (stored by pdf-tts);
# --with-registry-auth below passes them to the swarm. This explicit
# login is only needed when GHCR_USER/GHCR_TOKEN secrets are provided.
if [ -n "${GHCR_TOKEN:-}" ]; then
  echo "$GHCR_TOKEN" | docker login ghcr.io -u "${GHCR_USER:-iamleson98}" --password-stdin
fi

# ── 3. Record previous image for a documented rollback ───────────────
PREV_IMAGE=$(docker service inspect --format \
  '{{.Spec.TaskTemplate.ContainerSpec.Image}}' "${STACK}_backend" 2>/dev/null || true)
[ -n "$PREV_IMAGE" ] || PREV_IMAGE="(none)"
echo "previous image: $PREV_IMAGE"

# ── 4. Deploy the stack (volumes persist across releases) ────────────
echo "deploying $IMAGE"
IMAGE="$IMAGE" docker stack deploy --with-registry-auth -c stack.yml "$STACK"

# ── 5. Shared Caddy: append the datxevui.com site block once ─────────
if ! grep -q "$MARKER" "$SHARED_CADDYFILE" 2>/dev/null; then
  cat Caddyfile.datxevui >> "$SHARED_CADDYFILE"
  echo "Caddyfile: datxevui.com site block appended"
else
  echo "Caddyfile: site block already present"
fi

# ── 6. Hot-reload Caddy (zero downtime; restart fallback) ────────────
reload_caddy() {
  local task
  task=$(docker ps -q --filter name=pdf-tts_caddy | head -n1)
  if [ -n "$task" ] && docker exec "$task" caddy reload --config /etc/caddy/Caddyfile 2>&1; then
    echo "caddy reloaded (hot)"
    return 0
  fi
  echo "caddy hot-reload failed — restarting the caddy task (brief blip on :80/:443)"
  task=$(docker ps -q --filter name=pdf-tts_caddy | head -n1)
  [ -n "$task" ] && docker restart "$task"
}
reload_caddy

# ── 7. Health gate on the NEW backend task (180s budget) ─────────────
# All must pass before the deploy is declared successful:
#   a) the HEALTHY TASK's OWN image matches $IMAGE — the container's
#      Config.Image, which swarm resolves to "image:tag@sha256:…".
#      This is the authoritative check: the OLD task (previous image)
#      can be briefly healthy during the stop-first drain window, and
#      without this check the gate would pass before the new task
#      takes over.
#   b) the SERVICE SPEC image matches $IMAGE. A ROLLBACK reverts the
#      spec to the previous image: healthy-task + mismatched spec =
#      swarm auto-rollback (seen 2026-09-07: a transient "lease does
#      not exist" task rejection rolled the deploy back and the old
#      gate passed on the old task — the workflow went green while
#      the service kept running the previous image).
#   c) Docker health=healthy (the image's own HEALTHCHECK, curl
#      /health) plus an in-container `curl /health` — direct
#      confirmation, immune to the anti-scraping UA block (/health is
#      exempted in middleware). NOTE: `--filter ancestor=$IMAGE` does
#      NOT work — swarm resolves the tag to a digest at service
#      create, so the tag-only ancestor filter never matched
#      (false negative seen 2026-09-07).
#
# On ROLLBACK the stack deploy is retried ONCE: the "lease does not
# exist" rejection is a transient Docker 29 stack-deploy flake and the
# image is already pulled by then, so the second attempt usually
# converges.
wait_for_healthy() {
  for i in $(seq 1 90); do
    local t spec_img task_img
    t=$(docker ps -q --filter "name=${STACK}_backend" --filter "health=healthy" 2>/dev/null | head -n1)
    if [ -n "$t" ] && docker exec "$t" curl -sf http://localhost:8080/health >/dev/null 2>&1; then
      spec_img=$(docker service inspect --format \
        '{{.Spec.TaskTemplate.ContainerSpec.Image}}' "${STACK}_backend" 2>/dev/null)
      case "$spec_img" in
        "$IMAGE"|"$IMAGE@"*)
          # Spec is the new image — but the spec flips BEFORE the old
          # task drains (stop-first), so also require the healthy
          # task's OWN image to match (swarm sets the container's
          # Config.Image to the resolved "tag@digest").
          task_img=$(docker inspect --format '{{.Config.Image}}' "$t" 2>/dev/null)
          case "$task_img" in
            "$IMAGE"|"$IMAGE@"*)
              echo "backend healthy after ~$((i*2))s (task $t)"
              echo "task image:   $task_img"
              echo "service spec: $spec_img"
              return 0
              ;;
            *)
              # Old image still draining — new task hasn't taken over.
              ;;
          esac
          ;;
        *)
          echo "ROLLBACK DETECTED: healthy task $t but service spec is '$spec_img' (expected $IMAGE)"
          return 2
          ;;
      esac
    fi
    sleep 2
  done
  return 1
}

echo "waiting for /health ..."
rc=0
wait_for_healthy || rc=$?
if [ "$rc" -eq 2 ]; then
  echo "retrying the stack deploy once (transient rejection) ..."
  IMAGE="$IMAGE" docker stack deploy --with-registry-auth -c stack.yml "$STACK"
  rc=0
  wait_for_healthy || rc=$?
fi

if [ "$rc" -ne 0 ]; then
  echo "health check FAILED (rc=$rc) — last 80 backend log lines:"
  docker service logs --tail 80 "${STACK}_backend" || true
  echo "rollback:  docker service update --image ${PREV_IMAGE} ${STACK}_backend"
  exit 1
fi

docker stack ps "$STACK" --no-trunc --format \
  'table {{.Name}}\t{{.Image}}\t{{.CurrentState}}' | head -5
docker image prune -f >/dev/null 2>&1 || true
echo "deployed: $IMAGE"
echo "e2e (needs DNS): curl -I https://datxevui.com/health"
exit 0
