#!/usr/bin/env bash
# VeXeVN (datxevui.com) — idempotent Swarm-stack deploy on the shared node.
#
# Run by GitHub Actions (.github/workflows/deploy.yml) after each tag build:
#   IMAGE=ghcr.io/iamleson98/rust-be-template:v0.1.0 bash deploy.sh
#
# Expects next to this script: stack.yml, Caddyfile.datxevui
# Creates .env on the FIRST run (random JWT secret, 0600) — secrets are
# generated on the server and never leave it.
#
# What it does:
#   1. first-run .env           (JWT_SECRET via openssl)
#   1b. TURN env + coturn       (turn.sh — STUN/TURN relay for calls)
#   2. optional GHCR login      (private packages only)
#   3. docker stack deploy      (pulls $IMAGE, volumes persist)
#   4. guarantees exactly ONE datxevui.com site block in the shared
#      Caddyfile (strips stale blocks — old or new markers, duplicates
#      included — appends the canonical one, validates BEFORE swap;
#      writes IN-PLACE so the bind-mounted file stays in sync)
#   5. hot-reloads Caddy        (zero downtime; task-recreate fallback)
#   6. health gate: /health on the NEW backend task (verified against
#      the service spec image — detects swarm auto-rollback; retries
#      once on the transient "lease does not exist" rejection)
#
# Rollback on failure (documented, manual):
#   docker service update --image <PREV_IMAGE> datxevui_backend
set -euo pipefail

cd "$(cd "$(dirname "$0")" && pwd)"

STACK=datxevui
SHARED_CADDYFILE=/opt/pdf-tts/Caddyfile

[ -f stack.yml ]          || { echo "FATAL: stack.yml missing in $(pwd)"; exit 1; }
[ -f Caddyfile.datxevui ] || { echo "FATAL: Caddyfile.datxevui missing in $(pwd)"; exit 1; }
[ -f turn.sh ]            || { echo "FATAL: turn.sh missing in $(pwd)"; exit 1; }

# ── 1. First-run .env (secrets generated ON the server) ──────────────
if [ ! -f .env ]; then
  umask 077
  cat > .env <<EOF
# datxevui production env — generated by deploy.sh on first run.
# Non-secret defaults live in stack.yml; edit values here to override.
JWT_SECRET=$(openssl rand -hex 32)
EOF
  echo ".env created with a fresh random JWT_SECRET (0600)"
fi

# Export .env values so stack.yml ${VAR} interpolation picks them up.
set -a; . ./.env; set +a

# ── 1b. TURN relay (coturn) — BEFORE the stack deploy so the backend
# container is created with AUDIO_CALL_ICE_SERVERS already set. turn.sh
# is idempotent: first run generates TURN_SECRET + public-IP detection,
# later runs are no-ops unless the credentials change. Calls between
# peers on 5G/CGNAT and home WiFi NEED this relay to connect.
if TURN_FROM_DEPLOY=1 bash turn.sh; then
  # turn.sh may have appended vars — re-source so THIS deploy sees them.
  set -a; . ./.env; set +a
else
  echo "WARN: turn.sh failed — deploying without TURN changes (calls behind CGNAT may fail)"
fi

# The CD pipeline passes the exact image ref; manual runs may set it too.
: "${IMAGE:?IMAGE=<image-ref> env var is required (set by the CD pipeline)}"
: "${JWT_SECRET:?JWT_SECRET missing — check .env}"

# ── 1c. RustFS credentials (route media) — idempotent backfill ──────
# stack.yml hard-requires RUSTFS_ACCESS_KEY/SECRET_KEY; generate them
# on FIRST need (existing .env from before the media feature has no
# such keys) and re-source so THIS deploy sees them.
if ! grep -q '^RUSTFS_ACCESS_KEY=' .env 2>/dev/null; then
  umask 077
  {
    echo ""
    echo "# ── Route media (RustFS object storage) — added by deploy.sh ──"
    echo "RUSTFS_ACCESS_KEY=$(openssl rand -hex 16)"
    echo "RUSTFS_SECRET_KEY=$(openssl rand -hex 32)"
    echo "# Set after DNS + Cloudflare proxying for media.datxevui.com:"
    echo "#STORAGE_PUBLIC_BASE_URL=https://media.datxevui.com"
  } >> .env
  echo ".env: generated fresh RUSTFS_ACCESS_KEY/RUSTFS_SECRET_KEY"
fi
set -a; . ./.env; set +a

# ── 2. Optional GHCR login (private packages only) ───────────────────
# The node usually already has ghcr.io credentials (stored by pdf-tts);
# --with-registry-auth below passes them to the swarm. This explicit
# login is only needed when GHCR_USER/GHCR_TOKEN secrets are provided.
if [ -n "${GHCR_TOKEN:-}" ]; then
  echo "$GHCR_TOKEN" | docker login ghcr.io -u "${GHCR_USER:-iamleson98}" --password-stdin
fi

# ── 3. Record previous image for a documented rollback ───────────────
PREV_IMAGE=$(docker service inspect --format \
  '{{.Spec.TaskTemplate.ContainerSpec.Image}}' "${STACK}_backend" 2>/dev/null || true)
[ -n "$PREV_IMAGE" ] || PREV_IMAGE="(none)"
echo "previous image: $PREV_IMAGE"

# ── 4. Deploy the stack (volumes persist across releases) ────────────
echo "deploying $IMAGE"
IMAGE="$IMAGE" docker stack deploy --with-registry-auth -c stack.yml "$STACK"

# ── 5. Shared Caddy: exactly ONE datxevui.com site block ───────────
# 2026-09-08 outage post-mortem: the old "grep marker, else append"
# logic silently relied on deploy.sh and Caddyfile.datxevui staying in
# sync. The stack rename (vexevn → datxevui) updated deploy.sh's
# MARKER but not the snippet, so the grep NEVER matched and the block
# was appended on EVERY deploy → "ambiguous site definition:
# datxevui.com" → the shared Caddy crash-looped and took BOTH
# datxevui.com and pdf-tts down. Instead we REBUILD the tail of the
# shared Caddyfile deterministically:
#   a) strip everything from the first appended-block marker (old
#      '# vexevn-datxevui' or new '# datxevui-datxevui') to EOF —
#      kills stale AND duplicated blocks in one pass;
#   b) append exactly one canonical block from Caddyfile.datxevui;
#   c) validate the result in a throwaway caddy container BEFORE
#      touching the live file (a broken config can never reach the
#      edge);
#   d) write IN-PLACE ('cat >'), NEVER 'mv'/'cp' a replacement over
#      the path. The shared Caddyfile is bind-mounted into the
#      running caddy container as a SINGLE FILE: replacing it via mv
#      swaps the inode and the container keeps reading the OLD
#      content — a subsequent 'caddy reload' then "succeeds" while
#      still serving the old upstream (seen 2026-09-08: reload went
#      green, then 502 "lookup vexevn_backend: no such host" once the
#      old stack was removed). 'cat >' truncates and rewrites the
#      SAME inode, so the bind-mounted view stays in sync.
[ -f "$SHARED_CADDYFILE" ] || {
  echo "FATAL: shared Caddyfile $SHARED_CADDYFILE missing — is the pdf-tts stack deployed?"
  exit 1
}
NEXT=$(mktemp /tmp/Caddyfile.datxevui.next.XXXXXX)
awk 'BEGIN{p=1} /^# (vexevn|datxevui)-datxevui/{p=0} p' "$SHARED_CADDYFILE" > "$NEXT"
cat Caddyfile.datxevui >> "$NEXT"
n_blocks=$(grep -c '^datxevui\.com, www\.datxevui\.com' "$NEXT" || true)
if [ "$n_blocks" != "1" ]; then
  echo "FATAL: expected exactly 1 datxevui.com site block in the rebuilt Caddyfile, got $n_blocks"
  rm -f "$NEXT"
  exit 1
fi
if ! docker run --rm --entrypoint caddy \
     -v "$NEXT":/etc/caddy/Caddyfile:ro \
     caddy:2-alpine validate --config /etc/caddy/Caddyfile >/dev/null 2>&1; then
  echo "FATAL: rebuilt Caddyfile failed 'caddy validate' — NOT touching the live config;"
  echo "       the last good config is still serving. Inspect $NEXT for the cause."
  exit 1
fi
cp -a "$SHARED_CADDYFILE" "$SHARED_CADDYFILE.bak-$(date +%Y%m%d-%H%M%S)"
cat "$NEXT" > "$SHARED_CADDYFILE"   # in-place rewrite — same inode
chmod 644 "$SHARED_CADDYFILE"
rm -f "$NEXT"
echo "Caddyfile: exactly one datxevui.com site block (validated, in-place write)"

# ── 6. Hot-reload Caddy (zero downtime; task-recreate fallback) ─────
# reload reads the bind-mounted /etc/caddy/Caddyfile inside the
# container — valid because step 5 wrote the file IN-PLACE. On failure
# (dead admin endpoint, ancient caddy, or a stale-inode situation left
# behind by an earlier bad write) recreate the caddy task: a fresh
# container re-binds the host path and definitely sees the new config.
# Recreating is safe: caddy is stateless here (certs live in the
# pdf-tts_caddy_data volume); the cost is a brief blip on :80/:443.
reload_caddy() {
  local task
  # `|| true`: docker ps can take SIGPIPE when head exits after the
  # first line — under `set -euo pipefail` that 141 would abort the
  # deploy (seen in production 2026-09-11: exit code 141 AFTER the
  # health gate had already passed, reporting a false deploy failure).
  task=$(docker ps -q --filter name=pdf-tts_caddy | head -n1 || true)
  if [ -n "$task" ] && docker exec "$task" caddy reload --config /etc/caddy/Caddyfile 2>&1; then
    echo "caddy reloaded (hot)"
    return 0
  fi
  echo "caddy hot-reload failed — recreating the caddy task (brief blip on :80/:443)"
  docker service update --force pdf-tts_caddy
}
reload_caddy

# ── 7. Health gate on the NEW backend task (180s budget) ─────────────
# All must pass before the deploy is declared successful:
#   a) the HEALTHY TASK's OWN image matches $IMAGE — the container's
#      Config.Image, which swarm resolves to "image:tag@sha256:…".
#      This is the authoritative check: the OLD task (previous image)
#      can be briefly healthy during the stop-first drain window, and
#      without this check the gate would pass before the new task
#      takes over.
#   b) the SERVICE SPEC image matches $IMAGE. A ROLLBACK reverts the
#      spec to the previous image: healthy-task + mismatched spec =
#      swarm auto-rollback (seen 2026-09-07: a transient "lease does
#      not exist" task rejection rolled the deploy back and the old
#      gate passed on the old task — the workflow went green while
#      the service kept running the previous image).
#   c) Docker health=healthy (the image's own HEALTHCHECK, curl
#      /health) plus an in-container `curl /health` — direct
#      confirmation, immune to the anti-scraping UA block (/health is
#      exempted in middleware). NOTE: `--filter ancestor=$IMAGE` does
#      NOT work — swarm resolves the tag to a digest at service
#      create, so the tag-only ancestor filter never matched
#      (false negative seen 2026-09-07).
#
# On ROLLBACK the stack deploy is retried ONCE: the "lease does not
# exist" rejection is a transient Docker 29 stack-deploy flake and the
# image is already pulled by then, so the second attempt usually
# converges.
wait_for_healthy() {
  for i in $(seq 1 90); do
    local t spec_img task_img
    t=$(docker ps -q --filter "name=${STACK}_backend" --filter "health=healthy" 2>/dev/null | head -n1 || true)
    if [ -n "$t" ] && docker exec "$t" curl -sf http://localhost:8080/health >/dev/null 2>&1; then
      spec_img=$(docker service inspect --format \
        '{{.Spec.TaskTemplate.ContainerSpec.Image}}' "${STACK}_backend" 2>/dev/null)
      case "$spec_img" in
        "$IMAGE"|"$IMAGE@"*)
          # Spec is the new image — but the spec flips BEFORE the old
          # task drains (stop-first), so also require the healthy
          # task's OWN image to match (swarm sets the container's
          # Config.Image to the resolved "tag@digest").
          task_img=$(docker inspect --format '{{.Config.Image}}' "$t" 2>/dev/null)
          case "$task_img" in
            "$IMAGE"|"$IMAGE@"*)
              echo "backend healthy after ~$((i*2))s (task $t)"
              echo "task image:   $task_img"
              echo "service spec: $spec_img"
              return 0
              ;;
            *)
              # Old image still draining — new task hasn't taken over.
              ;;
          esac
          ;;
        *)
          echo "ROLLBACK DETECTED: healthy task $t but service spec is '$spec_img' (expected $IMAGE)"
          return 2
          ;;
      esac
    fi
    sleep 2
  done
  return 1
}

echo "waiting for /health ..."
rc=0
wait_for_healthy || rc=$?
if [ "$rc" -eq 2 ]; then
  echo "retrying the stack deploy once (transient rejection) ..."
  IMAGE="$IMAGE" docker stack deploy --with-registry-auth -c stack.yml "$STACK"
  rc=0
  wait_for_healthy || rc=$?
fi

if [ "$rc" -ne 0 ]; then
  echo "health check FAILED (rc=$rc) — last 80 backend log lines:"
  docker service logs --tail 80 "${STACK}_backend" || true
  echo "rollback:  docker service update --image ${PREV_IMAGE} ${STACK}_backend"
  exit 1
fi

# ── 7b. ICE env gate — the quoting minefield guard ──────────────────
# AUDIO_CALL_ICE_SERVERS travels .env → bash `source` → docker stack
# interpolation → container env. bash strips inner DOUBLE quotes from
# unquoted values, which silently breaks the JSON → backend pushes
# iceServers:[] → calls behind CGNAT stuck on "connecting" (production
# incident 2026-09-09). turn.sh now stores the value single-quoted;
# this gate fails the deploy if the running container got a mangled
# value, so the regression can never ship silently again.
ENVVAL=$(docker exec "$(docker ps -q --filter "name=${STACK}_backend" --filter "health=healthy" | head -n1 || true)" \
  env 2>/dev/null | grep '^AUDIO_CALL_ICE_SERVERS=' | cut -d= -f2- || true)
if echo "$ENVVAL" | grep -q '"urls"'; then
  echo "ICE env OK — TURN servers will be pushed to clients:"
  echo "  ${ENVVAL:0:120}…"
elif [ -z "$ENVVAL" ]; then
  echo "WARN: AUDIO_CALL_ICE_SERVERS unset in the backend (TURN disabled — calls across CGNAT will fail)"
else
  echo "FATAL: AUDIO_CALL_ICE_SERVERS lost its JSON quoting in the container env:"
  echo "  got: $ENVVAL"
  echo "turn.sh should single-quote the value in .env — check deploy/turn.sh ensure_env."
  exit 1
fi

# `|| true` — SIGPIPE-proof: the no-trunc table is WIDE (long image
# SHAs); when head exits after 5 lines docker takes SIGPIPE and, under
# pipefail + set -e, the script aborts with 141 skipping the bucket
# ensure + final exit 0. This exact race shipped v0.4.9 as a false
# "Deploy failure" while the stack was healthy.
docker stack ps "$STACK" --no-trunc --format \
  'table {{.Name}}\t{{.Image}}\t{{.CurrentState}}' | head -5 || true

# ── 9. Route media: ensure the RustFS bucket exists (idempotent) ────
# The rustfs task needs a few seconds after `stack deploy` before its
# S3 API answers; retry briefly, then best-effort (a missing bucket
# only breaks picture UPLOADS — not the rest of the site — and the
# next deploy retries). `mc mb` is a no-op for an existing bucket; the
# `anonymous set download` policy makes GETs (CDN origin reads) work
# without signatures while writes stay signed.
# NOTE: the minio/mc image has ENTRYPOINT ["mc"], so `sh` MUST be passed
# via --entrypoint — otherwise mc receives `sh` as its subcommand and
# the whole ensure silently fails. BUCKET must also be exported for
# `-e BUCKET` to forward it into the container.
BUCKET="${STORAGE_S3_BUCKET:-datxevui-media}"
export BUCKET
for i in 1 2 3 4 5 6; do
  if docker run --rm --network "${CADDY_NET:-pdf-tts_pdf-tts}" \
      --entrypoint sh \
      -e RUSTFS_ACCESS_KEY -e RUSTFS_SECRET_KEY -e BUCKET \
      minio/mc -c '
        mc alias set r http://datxevui_rustfs:9000 "$RUSTFS_ACCESS_KEY" "$RUSTFS_SECRET_KEY" &&
        mc mb "r/$BUCKET" && mc anonymous set download "r/$BUCKET"' 2>/dev/null; then
    echo "route media: bucket '$BUCKET' ready (public-read for GETs)"
    break
  fi
  [ "$i" = 6 ] && echo "WARN: bucket ensure failed (rustfs still starting?); picture uploads will 500 until the next deploy retries" || sleep 5
done

docker image prune -f >/dev/null 2>&1 || true
echo "deployed: $IMAGE"
echo "e2e (needs DNS): curl -I https://datxevui.com/health"
exit 0
