#!/usr/bin/env bash
# ┌──────────────────────────────────────────────────────────────────────┐
# │ Contabo VPS one-time bootstrap for the VeXeVN stack.                  │
# │                                                                       │
# │ Idempotent — safe to re-run. Run as root (or sudo) FROM the deploy/  │
# │ directory (it expects docker-compose.contabo.yml next to it):        │
# │                                                                       │
# │   sudo bash server-init.sh                    # tunnel mode (default) │
# │   sudo bash server-init.sh --direct          # + open 80/443 for CF   │
# │                                                                       │
# │ What it does:                                                         │
# │   1. Installs Docker Engine + compose plugin if missing               │
# │   2. Prepares /opt/vexevn (or $DEPLOY_DIR) with the compose stack     │
# │   3. Generates .env with a strong random JWT_SECRET                  │
# │   4. Locks the firewall down: SSH only (tunnel needs no ports)       │
# │   5. Enables unattended security upgrades (best effort)              │
# └──────────────────────────────────────────────────────────────────────┘
set -euo pipefail

DEPLOY_DIR="${DEPLOY_DIR:-/opt/vexevn}"
OPEN_WEB_PORTS=0
for arg in "$@"; do
  case "$arg" in
    --direct) OPEN_WEB_PORTS=1 ;;
    *) echo "unknown flag: $arg (supported: --direct)" >&2; exit 2 ;;
  esac
done

say()  { printf '\n\033[1;36m▶ %s\033[0m\n' "$*"; }
ok()   { printf '\033[1;32m✔ %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m⚠ %s\033[0m\n' "$*"; }

# ── 0. Preconditions ───────────────────────────────────────────────────
if [ "$(id -u)" -ne 0 ]; then
  echo "run as root:  sudo bash $0" >&2; exit 1
fi
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ ! -f "$SCRIPT_DIR/docker-compose.contabo.yml" ]; then
  echo "docker-compose.contabo.yml not found next to $0" >&2
  echo "run this from the repo's deploy/ directory (scp'd or cloned)" >&2
  exit 1
fi
command -v curl >/dev/null || { apt-get update -y && apt-get install -y curl; }

# ── 1. Docker Engine + compose plugin ──────────────────────────────────
say "1/5 Docker"
if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
  ok "Docker $(docker --version | awk '{print $3}' | tr -d ,) already installed"
else
  curl -fsSL https://get.docker.com | sh
  systemctl enable --now docker
  ok "Docker installed: $(docker --version)"
fi
if ! docker compose version >/dev/null 2>&1; then
  echo "docker compose plugin missing" >&2; exit 1
fi
ok "compose plugin: $(docker compose version --short)"

# ── 2. Deploy directory + stack files ──────────────────────────────────
say "2/5 Deploy dir: $DEPLOY_DIR"
mkdir -p "$DEPLOY_DIR"
for f in docker-compose.contabo.yml Caddyfile.cloudflare import-osm.sh; do
  if [ -f "$SCRIPT_DIR/$f" ]; then
    install -m 0644 "$SCRIPT_DIR/$f" "$DEPLOY_DIR/$f"
  fi
done
[ -x "$SCRIPT_DIR/import-osm.sh" ] && install -m 0755 "$SCRIPT_DIR/import-osm.sh" "$DEPLOY_DIR/import-osm.sh"
ok "stack files in place"

# ── 3. .env (never overwrite an existing one) ──────────────────────────
say "3/5 .env"
if [ -f "$DEPLOY_DIR/.env" ]; then
  ok ".env already exists — leaving untouched"
else
  JWT_SECRET=$(openssl rand -hex 32)
  # `|| ...` keeps the script alive on EOF (non-interactive runs).
  read -rp "Cloudflare Tunnel token (Zero Trust → Networks → Tunnels; blank to add later): " TUNNEL_TOKEN || TUNNEL_TOKEN=""
  read -rp "Public origin URL, e.g. https://vexevn.vn (for CORS/cookies): " ORIGIN || ORIGIN=""
  [ -n "$TUNNEL_TOKEN" ] || TUNNEL_TOKEN="PASTE_TUNNEL_TOKEN_HERE"
  [ -n "$ORIGIN" ] || ORIGIN="https://yourdomain.com"
  cat > "$DEPLOY_DIR/.env" <<EOF
# ── Generated by server-init.sh $(date -u +%FT%TZ) — edit freely ──
# Full key reference: .env.example in the repo root.

# ── Server ───────────────────────────────────────────────────────
RUST_LOG=info,backend=info,tower_http=warn
SERVER_REQUEST_TIMEOUT_SECS=30

# ── Database (SQLite on the app-data volume; migrations run on boot) ─
DATABASE_URL=sqlite:/app/data/app.db?mode=rwc

# ── JWT (random, generated once) ─────────────────────────────────
JWT_SECRET=${JWT_SECRET}

# ── Cookies (HTTPS-only behind Cloudflare) ───────────────────────
COOKIE_DOMAIN=
COOKIE_SECURE=true
COOKIE_SAMESITE=lax

# ── Cache / storage / worker (in-process; no extra containers) ───
CACHE_BACKEND=moka
STORAGE_BACKEND=local
STORAGE_LOCAL_ROOT=./storage
WORKER_BACKEND=db
SCHEDULER_ENABLED=true
SCHEDULER_TZ_OFFSET_MINUTES=420

# ── Rate limiting ────────────────────────────────────────────────
# NOTE: behind the tunnel every request reaches the backend from the
# cloudflared container IP, so the governor bucket is SHARED by all
# visitors. Keep it generous as a global safety net; do per-client
# limiting with a Cloudflare WAF rate rule (free plan supports it).
RATE_LIMIT_RPM=6000
RATE_LIMIT_BURST=1000

# ── Static files (baked into the image at /app/frontend/dist) ─────
STATIC_FILES_DIR=./frontend/dist
STATIC_FILES_CACHE_MAX_AGE=86400

# ── Tantivy place search (volumes; see import-osm.sh) ─────────────
SEARCH_INDEX_DIR=/app/index/osm-index
SEARCH_OSM_PBF_PATH=/app/data/vietnam-latest.osm.pbf

# ── CORS / OAuth base (same origin — backend serves the frontend) ─
CORS_ORIGINS=${ORIGIN}
OAUTH_REDIRECT_BASE_URL=${ORIGIN}
OAUTH_FRONTEND_URL=${ORIGIN}

# ── Cloudflare Tunnel (cloudflared container) ─────────────────────
TUNNEL_TOKEN=${TUNNEL_TOKEN}

# ── CI/CD deploy pin (set per-release by GitHub Actions) ──────────
APP_IMAGE=ghcr.io/iamleson98/rust-be-template:latest
EOF
  chmod 600 "$DEPLOY_DIR/.env"
  ok ".env created (JWT_SECRET randomized, chmod 600)"
  [ "$TUNNEL_TOKEN" = "PASTE_TUNNEL_TOKEN_HERE" ] && \
    warn "TUNNEL_TOKEN is a placeholder — edit $DEPLOY_DIR/.env before starting cloudflared"
fi

# ── 4. Firewall (UFW): SSH only by default ─────────────────────────────
say "4/5 Firewall"
if command -v ufw >/dev/null 2>&1; then
  ufw allow OpenSSH >/dev/null 2>&1 || true
  if [ "$OPEN_WEB_PORTS" -eq 1 ]; then
    ufw allow 80/tcp  >/dev/null 2>&1 || true
    ufw allow 443/tcp >/dev/null 2>&1 || true
  fi
  ufw --force enable
  ufw status verbose | head -n 8
  ok "UFW active: SSH$( [ "$OPEN_WEB_PORTS" -eq 1 ] && echo ' + 80 + 443' || echo ' only — tunnel needs no inbound ports')"
else
  warn "ufw not found — lock the firewall in the Contabo panel (allow TCP 22 only)"
fi

# ── 5. Unattended security upgrades (best effort) ───────────────────────
say "5/5 Security updates"
if apt-get install -y unattended-upgrades >/dev/null 2>&1; then
  systemctl enable --now unattended-upgrades >/dev/null 2>&1 || true
  ok "unattended-upgrades enabled"
else
  warn "could not enable unattended-upgrades (non-fatal)"
fi

# ── Next steps ──────────────────────────────────────────────────────────
cat <<EOF

Done. Next steps:

  1. (tunnel mode) In Cloudflare Zero Trust → Networks → Tunnels, add a
     Public Hostname to your tunnel routing to:  http://backend:8080
  2. Start the stack:
       cd $DEPLOY_DIR
       docker compose -f docker-compose.contabo.yml up -d
  3. Build the Tantivy place index (one-off, ~500 MB download):
       bash import-osm.sh
  4. Create the first admin account — visit /login and register; the
     first registered user becomes admin automatically.

  Future deploys are tag-driven from GitHub:
       git tag v1.0.1 && git push origin v1.0.1
     (.github/workflows/deploy.yml builds, pushes GHCR, SSHes here,
      and runs APP_IMAGE=<tag> docker compose up -d)
EOF
