/**
 * Shared display constants + local UI-only types for the Admin module.
 *
 * Entity types (Brand, Route, Schedule, PickupPoint, BusLayout, Place)
 * are now imported from `@/lib/api/types.gen` (auto-generated by
 * openapi-ts) — they match the backend exactly. This file only keeps
 * constants and UI-only discriminated unions that don't have a backend
 * counterpart.
 */

import { Wifi, Snowflake, Droplet, Plug, type LucideIcon } from 'lucide-react'

export const DAY_LABELS = ['T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'CN']
export const DAY_FULL = ['Thứ 2', 'Thứ 3', 'Thứ 4', 'Thứ 5', 'Thứ 6', 'Thứ 7', 'CN']

export const VEHICLE_LABELS: Record<string, string> = {
  limousine: 'Limousine',
  sleeper: 'Giường nằm',
  semi_sleeper: 'Giường nằm nửa',
  standard: 'Ghế ngồi',
  minivan: 'Minivan',
}

export const AMENITY_OPTIONS: { key: string; label: string; icon: LucideIcon }[] = [
  { key: 'wifi', label: 'Wifi', icon: Wifi },
  { key: 'ac', label: 'Điều hoà', icon: Snowflake },
  { key: 'water', label: 'Nước uống', icon: Droplet },
  { key: 'charging', label: 'Cắm sạc', icon: Plug },
]

export const PICKUP_TYPE_LABELS: Record<string, string> = {
  station: 'Bến xe',
  curb: 'Đón ven đường',
  on_request: 'Theo yêu cầu',
}

/** Discriminated union used by the delete-confirmation AlertDialog. */
export type DeleteTarget =
  | { kind: 'brand'; id: string; name: string }
  | { kind: 'route'; id: string; name: string }
  | { kind: 'schedule'; id: string; name: string }
  | { kind: 'pickup'; id: string; name: string }
  | null
