//! `backend entity generate` — generate SeaORM entities from the live DB.
//!
//! Shells out to `sea-orm-cli generate entity` (must be installed).
//! Reads `DATABASE_URL` from the environment and forwards it.

use std::path::Path;
use std::process::Command;

use anyhow::{bail, Context};

use crate::config::Config;

pub async fn run(output: &Path, with_relations: bool) -> anyhow::Result<()> {
    ensure_sea_orm_cli_available()?;
    cleanup_legacy_entity_files(output).context("cleaning legacy entity files")?;

    // Resolve DB URL via the same config path as the rest of the app,
    // so defaults and `.env` loading behave consistently.
    let cfg = Config::load().context("loading config")?;
    let db_url = cfg.database.url;

    // Detect backend from the URL scheme.
    let backend = if db_url.starts_with("postgres://") || db_url.starts_with("postgresql://") {
        "postgres"
    } else if db_url.starts_with("sqlite://") {
        "sqlite"
    } else {
        bail!(
            "unsupported DATABASE_URL scheme: {db_url}\n\
             must start with `postgres://`, `postgresql://`, or `sqlite://`"
        )
    };

    println!("→ sea-orm-cli generate entity (backend: {backend})");
    println!("  output: {}", output.display());
    println!("  database: {db_url}");

    let mut cmd = Command::new("sea-orm-cli");
    cmd.arg("generate").arg("entity");
    cmd.arg("--output-dir").arg(output);
    cmd.arg("--database-url").arg(&db_url);
    cmd.arg("--with-serde").arg("both");
    // sea-orm-cli v2 removed `--with-relations`; relations are generated
    // by default. Keep the CLI flag for backward compatibility and
    // surface a notice when users pass `--with-relations=false`.
    if !with_relations {
        println!(
            "note: `--with-relations=false` is ignored with sea-orm-cli v2; relations are generated by default"
        );
    }
    // Keep defaults so this works across sea-orm-cli versions.

    let status = cmd
        .status()
        .context("spawning sea-orm-cli — is it installed and on PATH?")?;
    if !status.success() {
        bail!("sea-orm-cli exited with status {status}");
    }

    println!("✓ entities generated to {}", output.display());
    println!();
    println!("next steps:");
    println!("  1. Review the generated files under {}", output.display());
    println!("  2. If a migration was also added, run:  backend migrate up");
    Ok(())
}

fn cleanup_legacy_entity_files(output: &Path) -> anyhow::Result<()> {
    // Legacy sea-orm-codegen v1 filenames (singular) can coexist with v2
    // plural files and cause confusion. Remove only known generated legacy
    // files under the chosen output directory.
    let legacy = [
        "permission.rs",
        "post.rs",
        "refresh_token.rs",
        "role_permission.rs",
        "role.rs",
        "user_role.rs",
        "user.rs",
    ];

    for name in legacy {
        let path = output.join(name);
        if path.is_file() {
            std::fs::remove_file(&path)
                .with_context(|| format!("removing {}", path.display()))?;
            println!("removed legacy entity file: {}", path.display());
        }
    }

    Ok(())
}

fn ensure_sea_orm_cli_available() -> anyhow::Result<()> {
    // Probe by executing `--version` so command resolution uses OS rules
    // (including PATHEXT on Windows).
    match Command::new("sea-orm-cli").arg("--version").status() {
        Ok(status) if status.success() => Ok(()),
        Ok(_) => Ok(()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            bail!(
                "`sea-orm-cli` not found on PATH.\n\
                 Install it with:  cargo install sea-orm-cli\n\
                 Then re-run:     backend entity-generate"
            )
        }
        Err(e) => Err(e).context("failed to check `sea-orm-cli --version`")?,
    }
}
